LCFIPlus: lcfiplus::EventNavigator Class Reference
lcfiplus::EventNavigator Class Reference
Event display for LCFIPlus.
#include <EventNavigator.h>
Public Member Functions
EventNavigator (const char *input, int start=0)
Constructor.
~EventNavigator ()
void Fwd ()
Display next event.
void Bck ()
void drawEvent (Event *event)
Draws given event.
Detailed Description
Event display for LCFIPlus.
The graphics is based on the TEve framework for ROOT. Adapted from the <a href="http://llr.in2p3.fr/~ruan/ILDDisplay/>Druid event display.
Author
T. Tanabe, ICEPP, The University of Tokyo
Version
$Id$
Constructor & Destructor Documentation
EventNavigator()
lcfiplus::EventNavigator::EventNavigator (const char * input, int start = 0)
Constructor.
Parameters
[in] input input file which contains events to inspect.
[in] start skips given number of events.
References lcfiplus::LCIOStorer::Next().
~EventNavigator()
lcfiplus::EventNavigator::~EventNavigator ()
Member Function Documentation
Bck()
void lcfiplus::EventNavigator::Bck ()
drawEvent()
void lcfiplus::EventNavigator::drawEvent (Event * event)
Draws given event.
References lcfiplus::tpar::d0, lcfiplus::Globals::getBField(), lcfiplus::Track::getCharge(), lcfiplus::MCParticle::getCharge(), lcfiplus::Vertex::getChi2(), lcfiplus::Track::getD0(), lcfiplus::MCParticle::getEx(), lcfiplus::MCParticle::getEy(), lcfiplus::MCParticle::getEz(), lcfiplus::MCParticle::getFlavorTagCategory(), lcfiplus::Track::getPDG(), lcfiplus::MCParticle::getPDG(), lcfiplus::Track::getPhi(), lcfiplus::Vertex::getTracks(), lcfiplus::MCParticle::getVertex(), lcfiplus::Vertex::getX(), lcfiplus::Vertex::getY(), lcfiplus::Vertex::getZ(), lcfiplus::Track::getZ0(), lcfiplus::Globals::Instance(), lcfiplus::MCParticle::isStableTrack(), and lcfiplus::tpar::z0.
Referenced by Fwd().
Fwd()
void lcfiplus::EventNavigator::Fwd ()
Display next event.
References drawEvent(), lcfiplus::Event::Instance(), and lcfiplus::LCIOStorer::Next().
The documentation for this class was generated from the following files:
EventNavigator.h
EventNavigator.cc