LCFIPlus: lcfiplus::Algorithm Class Reference
lcfiplus::Algorithm Class Reference abstract
#include <lcfiplus.h>
Public Member Functions
Algorithm ()
virtual ~Algorithm ()
virtual void init (Parameters *param)
virtual void process ()=0
virtual void end ()
Protected Member Functions
Parameters * GetParam () const
Constructor & Destructor Documentation
Algorithm()
lcfiplus::Algorithm::Algorithm () inline
~Algorithm()
virtual lcfiplus::Algorithm::~Algorithm () inline virtual
Member Function Documentation
end()
virtual void lcfiplus::Algorithm::end () inline virtual
Reimplemented in lcfiplus::TestAlgoV0, lcfiplus::FlavtagReader, lcfiplus::VertexAnalysis, lcfiplus::TestAlgo, lcfiplus::ZHHAlgo, lcfiplus::MakeROOTFileBB, lcfiplus::JetVertexRefiner, lcfiplus::JetClustering, lcfiplus::BuildUpVertex, lcfiplus::FlavorTag, lcfiplus::ReadMVA, lcfiplus::TrackNtuple, lcfiplus::TrainMVA, lcfiplus::VertexNtuple, lcfiplus::VertexFindingwithDL, lcfiplus::MakeNtuple, lcfiplus::MakeROOTFileCC, lcfiplus::PrimaryVertexFinder, and lcfiplus::VertexMassRecovery.
GetParam()
Parameters* lcfiplus::Algorithm::GetParam () const inline protected
init()
virtual void lcfiplus::Algorithm::init (Parameters * param) inline virtual
Reimplemented in lcfiplus::TestAlgoV0, lcfiplus::FlavtagReader, lcfiplus::VertexAnalysis, lcfiplus::TestAlgo, lcfiplus::ZHHAlgo, lcfiplus::MakeROOTFileBB, lcfiplus::JetVertexRefiner, lcfiplus::JetClustering, lcfiplus::BuildUpVertex, lcfiplus::FlavorTag, lcfiplus::ReadMVA, lcfiplus::TrackNtuple, lcfiplus::TrainMVA, lcfiplus::VertexNtuple, lcfiplus::VertexFindingwithDL, lcfiplus::MakeNtuple, lcfiplus::MakeROOTFileCC, lcfiplus::PrimaryVertexFinder, and lcfiplus::VertexMassRecovery.
Referenced by lcfiplus::VertexMassRecovery::init(), lcfiplus::PrimaryVertexFinder::init(), lcfiplus::MakeROOTFileCC::init(), lcfiplus::MakeNtuple::init(), lcfiplus::VertexFindingwithDL::init(), lcfiplus::TrainMVA::init(), lcfiplus::VertexNtuple::init(), lcfiplus::TrackNtuple::init(), lcfiplus::ReadMVA::init(), lcfiplus::FlavorTag::init(), LcfiplusProcessor::init(), lcfiplus::BuildUpVertex::init(), lcfiplus::JetClustering::init(), lcfiplus::JetVertexRefiner::init(), lcfiplus::MakeROOTFileBB::init(), lcfiplus::ZHHAlgo::init(), lcfiplus::TestAlgo::init(), lcfiplus::VertexAnalysis::init(), lcfiplus::FlavtagReader::init(), and lcfiplus::TestAlgoV0::init().
process()
virtual void lcfiplus::Algorithm::process () pure virtual
Implemented in lcfiplus::TestAlgoV0, lcfiplus::FlavtagReader, lcfiplus::VertexAnalysis, lcfiplus::TestAlgo, lcfiplus::ZHHAlgo, lcfiplus::MakeROOTFileBB, lcfiplus::JetVertexRefiner, lcfiplus::JetClustering, lcfiplus::BuildUpVertex, lcfiplus::FlavorTag, lcfiplus::ReadMVA, lcfiplus::TrackNtuple, lcfiplus::TrainMVA, lcfiplus::VertexNtuple, lcfiplus::VertexFindingwithDL, lcfiplus::MakeNtuple, lcfiplus::MakeROOTFileCC, lcfiplus::PrimaryVertexFinder, and lcfiplus::VertexMassRecovery.
The documentation for this class was generated from the following file:
lcfiplus.h