LCFIPlus: lcfiplus::TrainMVA Class Reference
lcfiplus::TrainMVA Class Reference
Lcfiplus algorithm for training classifications using TMVA.
#include <TrainMVA.h>
Classes
struct InputFileInfo
Public Member Functions
TrainMVA ()
virtual ~TrainMVA ()
void init (Parameters *param)
void process ()
void end ()
Public Member Functions inherited from lcfiplus::Algorithm
Algorithm ()
virtual ~Algorithm ()
Additional Inherited Members
Protected Member Functions inherited from lcfiplus::Algorithm
Parameters * GetParam () const
Detailed Description
Lcfiplus algorithm for training classifications using TMVA.
Author
T. Tanabe, ICEPP, The University of Tokyo
Version
$Id$
Constructor & Destructor Documentation
TrainMVA()
lcfiplus::TrainMVA::TrainMVA () inline
~TrainMVA()
virtual lcfiplus::TrainMVA::~TrainMVA () inline virtual
Member Function Documentation
end()
void TrainMVA::end () virtual
Reimplemented from lcfiplus::Algorithm.
References lcfiplus::FlavtagCategory::definition, lcfiplus::FlavtagCategory::preselection, lcfiplus::FlavtagCategory::spec, and lcfiplus::FlavtagCategory::vars.
init()
void TrainMVA::init (Parameters * param) virtual
Reimplemented from lcfiplus::Algorithm.
References lcfiplus::FlavtagCategory::definition, lcfiplus::Parameters::fetchArray(), lcfiplus::Parameters::get(), lcfiplus::Algorithm::init(), lcfiplus::FlavtagCategory::preselection, lcfiplus::FlavtagCategory::spec, and lcfiplus::FlavtagCategory::vars.
process()
void TrainMVA::process () virtual
Implements lcfiplus::Algorithm.
The documentation for this class was generated from the following files:
TrainMVA.h
TrainMVA.cc