LCFIPlus: lcfiplus::VertexSelector Class Reference
lcfiplus::VertexSelector Class Reference
#include <VertexSelector.h>
Public Member Functions
vector< const Vertex * > operator() (VertexVec &vertices, VertexSelectorConfig &config, vector< const Track *> &residualTracks, bool addTracks)
vector< Vertex * > operator() (const vector< Vertex *> &vertices, VertexSelectorConfig &config, vector< const Track *> &residualTracks, bool addTracks)
vector< const Vertex * > operator() (VertexVec &vertices, VertexSelectorConfig &config)
void operator() (vector< Vertex *> &vertices, VertexSelectorConfig &config)
bool isV0 (const Vertex *vtx, const VertexSelectorConfig &cfg, const Vertex *primary)
bool passesCut (const Vertex *vtx, const VertexSelectorConfig &cfg, const Vertex *primary=0)
VertexSelector ()
~VertexSelector ()
Constructor & Destructor Documentation
VertexSelector()
lcfiplus::VertexSelector::VertexSelector () inline
~VertexSelector()
lcfiplus::VertexSelector::~VertexSelector () inline
Member Function Documentation
isV0()
bool lcfiplus::VertexSelector::isV0 (const Vertex * vtx, const VertexSelectorConfig & cfg, const Vertex * primary) inline
References lcfiplus::VertexSelectorConfig::convdirdot, lcfiplus::VertexSelectorConfig::convdist, lcfiplus::VertexSelectorConfig::convmass, lcfiplus::Vertex::getPos(), lcfiplus::Vertex::getTracks(), lcfiplus::VertexSelectorConfig::k0dirdot, lcfiplus::VertexSelectorConfig::k0width, lcfiplus::VertexSelectorConfig::l0dirdot, lcfiplus::VertexSelectorConfig::l0width, lcfiplus::VertexSelectorConfig::rejectconv, lcfiplus::VertexSelectorConfig::rejectk0, and lcfiplus::VertexSelectorConfig::rejectl0.
operator()() [1/4]
vector<const Vertex*> lcfiplus::VertexSelector::operator() (VertexVec & vertices, VertexSelectorConfig & config, vector< const Track *> & residualTracks, bool addTracks) inline
operator()() [2/4]
vector<Vertex*> lcfiplus::VertexSelector::operator() (const vector< Vertex *> & vertices, VertexSelectorConfig & config, vector< const Track *> & residualTracks, bool addTracks) inline
operator()() [3/4]
vector<const Vertex*> lcfiplus::VertexSelector::operator() (VertexVec & vertices, VertexSelectorConfig & config) inline
operator()() [4/4]
void lcfiplus::VertexSelector::operator() (vector< Vertex *> & vertices, VertexSelectorConfig & config) inline
passesCut()
bool lcfiplus::VertexSelector::passesCut (const Vertex * vtx, const VertexSelectorConfig & cfg, const Vertex * primary = 0) inline
References lcfiplus::Vertex::getPos(), lcfiplus::VertexSelectorConfig::maxpos, lcfiplus::VertexSelectorConfig::minpos, lcfiplus::VertexSelectorConfig::rejectconv, lcfiplus::VertexSelectorConfig::rejectdist, lcfiplus::VertexSelectorConfig::rejectdistnegative, lcfiplus::VertexSelectorConfig::rejectdistor, lcfiplus::VertexSelectorConfig::rejectk0, and lcfiplus::VertexSelectorConfig::rejectl0.
Referenced by lcfiplus::MakeROOTFileCC::process(), and lcfiplus::MakeROOTFileBB::process().
The documentation for this class was generated from the following file:
VertexSelector.h