LCFIPlus: lcfiplus::VertexMassRecovery Class Reference
lcfiplus::VertexMassRecovery Class Reference
#include <VertexMassRecovery.h>
Public Member Functions
VertexMassRecovery ()
virtual ~VertexMassRecovery ()
void init (Parameters *param)
void process ()
void end ()
ClassDef (VertexMassRecovery, 1)
Public Member Functions inherited from lcfiplus::Algorithm
Algorithm ()
virtual ~Algorithm ()
Additional Inherited Members
Protected Member Functions inherited from lcfiplus::Algorithm
Parameters * GetParam () const
Constructor & Destructor Documentation
VertexMassRecovery()
lcfiplus::VertexMassRecovery::VertexMassRecovery () inline
~VertexMassRecovery()
virtual lcfiplus::VertexMassRecovery::~VertexMassRecovery () inline virtual
Member Function Documentation
ClassDef()
lcfiplus::VertexMassRecovery::ClassDef (VertexMassRecovery , 1)
end()
void lcfiplus::VertexMassRecovery::end () virtual
Reimplemented from lcfiplus::Algorithm.
init()
void lcfiplus::VertexMassRecovery::init (Parameters * param) virtual
Reimplemented from lcfiplus::Algorithm.
References lcfiplus::Parameters::get(), lcfiplus::Algorithm::init(), lcfiplus::Event::Instance(), lcfiplus::EventStore::JET_WRITE_VERTEX, lcfiplus::EventStore::PERSIST, and lcfiplus::EventStore::Register().
process()
void lcfiplus::VertexMassRecovery::process () virtual
Implements lcfiplus::Algorithm.
References lcfiplus::Jet::add(), lcfiplus::Pi0VertexFinder::Corr_VtxVect(), lcfiplus::Pi0VertexFinder::Get_nPi0(), lcfiplus::Vertex::getPos(), lcfiplus::Pi0VertexFinder::Initialize(), lcfiplus::Event::Instance(), lcfiplus::Pi0VertexFinder::Make_GammaVector(), lcfiplus::Pi0VertexFinder::Reco_Pi0s(), and lcfiplus::Track::swapEnergy().
The documentation for this class was generated from the following files:
VertexMassRecovery.h
VertexMassRecovery.cc