LCFIPlus: lcfiplus::TreeStorer Class Reference
lcfiplus::TreeStorer Class Reference
#include <TreeStorer.h>
Public Types
enum { mode_input, mode_output }
Public Member Functions
TreeStorer (const char *filename, const char *treename, int mode)
virtual ~TreeStorer ()
void Register (const char *name)
void RegisterAll ()
void Fill ()
void Write ()
void GetEntry (int n)
TTree * GetTree ()
int GetEntries () const
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
mode_input
mode_output
Constructor & Destructor Documentation
TreeStorer()
lcfiplus::TreeStorer::TreeStorer (const char * filename, const char * treename, int mode)
References mode_input.
~TreeStorer()
lcfiplus::TreeStorer::~TreeStorer () virtual
Member Function Documentation
Fill()
void lcfiplus::TreeStorer::Fill ()
References mode_output.
GetEntries()
int lcfiplus::TreeStorer::GetEntries () const inline
GetEntry()
void lcfiplus::TreeStorer::GetEntry (int n)
References mode_input.
GetTree()
TTree* lcfiplus::TreeStorer::GetTree () inline
Register()
void lcfiplus::TreeStorer::Register (const char * name)
References lcfiplus::EventStore::GetClassName(), lcfiplus::EventStore::GetObject(), lcfiplus::Event::Instance(), mode_input, and lcfiplus::EventStore::RegisterObject().
Referenced by RegisterAll().
RegisterAll()
void lcfiplus::TreeStorer::RegisterAll ()
References mode_input, and Register().
Write()
void lcfiplus::TreeStorer::Write ()
References mode_output.
The documentation for this class was generated from the following files:
TreeStorer.h
TreeStorer.cc