LCFIPlus: lcfiplus::TrackNtuple Class Reference
lcfiplus::TrackNtuple Class Reference
Making track d0/z0 ntuple needed for flavor tagging.
#include <TrackNtuple.h>
Public Member Functions
TrackNtuple ()
virtual ~TrackNtuple ()
void init (Parameters *param)
void process ()
void end ()
Public Member Functions inherited from lcfiplus::Algorithm
Algorithm ()
virtual ~Algorithm ()
Additional Inherited Members
Protected Member Functions inherited from lcfiplus::Algorithm
Parameters * GetParam () const
Detailed Description
Making track d0/z0 ntuple needed for flavor tagging.
Should be rerun when vertex configuration is changed. Run TrackProb.C with hadded output files of this algorithm.
Author
T. Suehara, Dept. of Physics, Kyushu University
Version
$Id$
Constructor & Destructor Documentation
TrackNtuple()
lcfiplus::TrackNtuple::TrackNtuple () inline
~TrackNtuple()
virtual lcfiplus::TrackNtuple::~TrackNtuple () inline virtual
Member Function Documentation
end()
void lcfiplus::TrackNtuple::end () virtual
Reimplemented from lcfiplus::Algorithm.
init()
void lcfiplus::TrackNtuple::init (Parameters * param) virtual
Reimplemented from lcfiplus::Algorithm.
References lcfiplus::Parameters::get(), lcfiplus::Algorithm::init(), lcfiplus::Event::Instance(), and lcfiplus::Event::setDefaultPrimaryVertex().
process()
void lcfiplus::TrackNtuple::process () virtual
Implements lcfiplus::Algorithm.
References lcfiplus::Jet::getAllTracks(), lcfiplus::Event::Instance(), lcfiplus::algoSigProb::signedD0(), lcfiplus::algoSigProb::signedD0Significance(), lcfiplus::algoSigProb::signedZ0(), lcfiplus::algoSigProb::signedZ0Significance(), and lcfiplus::algoSigProb::trackSelectionForFlavorTag().
The documentation for this class was generated from the following files:
TrackNtuple.h
TrackNtuple.cc