LCFIPlus: lcfiplus::GeometryHandler Class Reference
lcfiplus::GeometryHandler Class Reference
#include <geometry.h>
Classes
class PointFitDerivFunctor
class PointFitFunctor
Public Member Functions
double PointFit (const vector< PointBase *> &points, const TVector3 &initial, Point *result=0)
double HelixPointFit (const vector< Helix *> &helices, Point *result=0)
Static Public Member Functions
static GeometryHandler * Instance ()
Member Function Documentation
HelixPointFit()
double lcfiplus::GeometryHandler::HelixPointFit (const vector< Helix *> & helices, Point * result = 0)
References lcfiplus::Point::GetPos(), and lcfiplus::verbose.
Referenced by lcfiplus::VertexFitterSimple< Iterator >::operator()().
Instance()
GeometryHandler * lcfiplus::GeometryHandler::Instance () static
Referenced by lcfiplus::Helix::LongitudinalDeviation().
PointFit()
double lcfiplus::GeometryHandler::PointFit (const vector< PointBase *> & points, const TVector3 & initial, Point * result = 0)
References lcfiplus::algoEtc::min(), lcfiplus::Point::SetPosErr(), and lcfiplus::verbose.
Referenced by lcfiplus::VertexFitterSimple< Iterator >::getChi2(), lcfiplus::Helix::LongitudinalDeviation(), and lcfiplus::VertexFitterSimple< Iterator >::operator()().
The documentation for this class was generated from the following files:
geometry.h
geometry.cc