LCFIPlus: lcfiplus::FtD0bProb Class Reference
lcfiplus::FtD0bProb Class Reference
Public Member Functions
FtD0bProb ()
void process ()
Public Member Functions inherited from lcfiplus::FTAlgo
FTAlgo (string name)
virtual ~FTAlgo ()
void setEvent (const Event *event, const Vertex *privtx)
void setJet (const Jet *jet)
void setNHitsJointProbD0 (int value)
void setNHitsJointProbZ0 (int value)
void setNHitsMostSignificantTrack (int value)
float getValue ()
const string & getName () const
float * getValueAddress ()
virtual void processEvent ()
Additional Inherited Members
Protected Attributes inherited from lcfiplus::FTAlgo
const Event * _event
const Vertex * _privtx
const Jet * _jet
int _nhitsJointProbD0
int _nhitsJointProbZ0
int _nhitsMostSignificantTrack
float _result
string _name
Constructor & Destructor Documentation
FtD0bProb()
lcfiplus::FtD0bProb::FtD0bProb () inline
Member Function Documentation
process()
void lcfiplus::FtD0bProb::process () inline virtual
Reimplemented from lcfiplus::FTAlgo.
References lcfiplus::FTManager::getInstance(), lcfiplus::FTManager::getIPProbHolder(), and lcfiplus::algoSigProb::trackD0Significance().
The documentation for this class was generated from the following file:
FlavorTag.cc