LCFIPlus: lcfiplus::JetClustering Class Reference
lcfiplus::JetClustering Class Reference
#include <process.h>
Public Member Functions
JetClustering ()
virtual ~JetClustering ()
void init (Parameters *param)
void process ()
void end ()
ClassDef (JetClustering, 1)
Public Member Functions inherited from lcfiplus::Algorithm
Algorithm ()
virtual ~Algorithm ()
Additional Inherited Members
Protected Member Functions inherited from lcfiplus::Algorithm
Parameters * GetParam () const
Constructor & Destructor Documentation
JetClustering()
lcfiplus::JetClustering::JetClustering () inline
~JetClustering()
virtual lcfiplus::JetClustering::~JetClustering () inline virtual
Member Function Documentation
ClassDef()
lcfiplus::JetClustering::ClassDef (JetClustering , 1)
end()
void lcfiplus::JetClustering::end () virtual
Reimplemented from lcfiplus::Algorithm.
init()
void lcfiplus::JetClustering::init (Parameters * param) virtual
Reimplemented from lcfiplus::Algorithm.
References lcfiplus::Parameters::fetchArray(), lcfiplus::EventStore::Get(), lcfiplus::Parameters::get(), lcfiplus::Algorithm::init(), lcfiplus::Event::Instance(), lcfiplus::EventStore::JET_WRITE_VERTEX, lcfiplus::EventStore::PERSIST, and lcfiplus::EventStore::Register().
process()
void lcfiplus::JetClustering::process () virtual
Implements lcfiplus::Algorithm.
References lcfiplus::Parameters::add(), lcfiplus::Jet::addParam(), lcfiplus::JetConfig::algo, lcfiplus::JetConfig::alphaParameter, lcfiplus::JetConfig::betaParameter, lcfiplus::JetConfig::gammaParameter, lcfiplus::EventStore::Get(), lcfiplus::Event::Instance(), lcfiplus::VertexSelectorConfig::k0width, lcfiplus::VertexSelectorConfig::maxpos, lcfiplus::VertexSelectorConfig::minpos, lcfiplus::JetConfig::muonIDExternal, lcfiplus::JetConfig::muonIDMaxDist, lcfiplus::JetConfig::muonIDMinD0Sig, lcfiplus::JetConfig::muonIDMinEnergy, lcfiplus::JetConfig::muonIDMinProb, lcfiplus::JetConfig::muonIDMinZ0Sig, lcfiplus::JetConfig::nJet, lcfiplus::VertexSelectorConfig::rejectdist, lcfiplus::VertexSelectorConfig::rejectk0, lcfiplus::JetConfig::rParameter, lcfiplus::JetConfig::useBeamJets, lcfiplus::JetConfig::useMuonID, lcfiplus::JetConfig::YaddLL, lcfiplus::JetConfig::YaddVL, lcfiplus::JetConfig::YaddVV, and lcfiplus::JetConfig::Ycut.
The documentation for this class was generated from the following files:
process.h
process.cc