LCFIPlus: lcfiplus::FTAlgo Class Reference
lcfiplus::FTAlgo Class Reference
#include <flavtag.h>
Public Member Functions
FTAlgo (string name)
virtual ~FTAlgo ()
void setEvent (const Event *event, const Vertex *privtx)
void setJet (const Jet *jet)
void setNHitsJointProbD0 (int value)
void setNHitsJointProbZ0 (int value)
void setNHitsMostSignificantTrack (int value)
float getValue ()
const string & getName () const
float * getValueAddress ()
virtual void processEvent ()
virtual void process ()
Protected Attributes
const Event * _event
const Vertex * _privtx
const Jet * _jet
int _nhitsJointProbD0
int _nhitsJointProbZ0
int _nhitsMostSignificantTrack
float _result
string _name
Constructor & Destructor Documentation
FTAlgo()
lcfiplus::FTAlgo::FTAlgo (string name) inline
~FTAlgo()
virtual lcfiplus::FTAlgo::~FTAlgo () inline virtual
Member Function Documentation
getName()
const string& lcfiplus::FTAlgo::getName () const inline
References _name.
Referenced by lcfiplus::FTManager::getVarAddress(), lcfiplus::FTManager::openFile(), lcfiplus::FTManager::openTree(), and lcfiplus::FTManager::process().
getValue()
float lcfiplus::FTAlgo::getValue ()
References _result.
getValueAddress()
float* lcfiplus::FTAlgo::getValueAddress () inline
References _result.
Referenced by lcfiplus::FTManager::getVarAddress(), lcfiplus::FTManager::openFile(), and lcfiplus::FTManager::openTree().
process()
virtual void lcfiplus::FTAlgo::process () inline virtual
Reimplemented in lcfiplus::FtNBNess, lcfiplus::FtBNessMass, lcfiplus::FtBNess3, lcfiplus::FtBNess2, lcfiplus::FtBNess1, lcfiplus::FtBNess0, lcfiplus::FtNPi0s2, lcfiplus::FtNPi0s1, lcfiplus::FtPi0MomentumAll, lcfiplus::FtPi0Momentum2, lcfiplus::FtPi0Momentum1, lcfiplus::FtCorrVtxMomentumAll, lcfiplus::FtCorrVtxMomentum2, lcfiplus::FtCorrVtxMomentum1, lcfiplus::FtCorrVtxMassAll, lcfiplus::FtCorrVtxMass2, lcfiplus::FtCorrVtxMass1, lcfiplus::FtZ0cProbIP, lcfiplus::FtZ0bProbIP, lcfiplus::FtZ0qProb2, lcfiplus::FtZ0qProb, lcfiplus::FtZ0cProb2, lcfiplus::FtZ0cProb, lcfiplus::FtZ0bProb2, lcfiplus::FtZ0bProb, lcfiplus::FtD0cProbIP, lcfiplus::FtD0bProbIP, lcfiplus::FtD0qProbSigned, lcfiplus::FtD0cProbSigned, lcfiplus::FtD0bProbSigned, lcfiplus::FtD0qProb2, lcfiplus::FtD0qProb, lcfiplus::FtD0cProb2, lcfiplus::FtD0cProb, lcfiplus::FtD0bProb2, lcfiplus::FtD0bProb, lcfiplus::FtMCNC, lcfiplus::FtMCNB, lcfiplus::FtMCNElectron, lcfiplus::FtMCNMuon, lcfiplus::FtNMuonPID, lcfiplus::FtNElectronPID, lcfiplus::FtNElectron, lcfiplus::FtNMuon, lcfiplus::FtVtxLongitudinalDeviation, lcfiplus::FtNSecTracks, lcfiplus::FtTrkMass2, lcfiplus::FtTrkMass, lcfiplus::FtSphericity, lcfiplus::FtJProbZ25Sigma, lcfiplus::FtJProbR25Sigma, lcfiplus::FtJProbZ2, lcfiplus::FtJProbR2, lcfiplus::FtJProbZ5Sigma, lcfiplus::FtJProbR5Sigma, lcfiplus::FtJProbZ, lcfiplus::FtJProbR, lcfiplus::FtTrk2PtByJetE, lcfiplus::FtTrk1PtByJetE, lcfiplus::FtTrk2Pt, lcfiplus::FtTrk1Pt, lcfiplus::FtTrk2Z0Sig, lcfiplus::FtTrk1Z0Sig, lcfiplus::FtTrk2D0Sig, lcfiplus::FtTrk1D0Sig, lcfiplus::FtVtxMult2, lcfiplus::FtVtxMult1, lcfiplus::FtVtxMult, lcfiplus::FtVtxMass2, lcfiplus::FtVtxMass1, lcfiplus::FtVtxMass, lcfiplus::FtVtxProb, lcfiplus::FtVtxMassPtCorr, lcfiplus::FtVtxMom2ByJetE, lcfiplus::FtVtxMom1ByJetE, lcfiplus::FtVtxMomByJetE, lcfiplus::FtVtxMom2, lcfiplus::FtVtxMom1, lcfiplus::FtVtxMom, lcfiplus::FtVtxDirAng12TimesJetE, lcfiplus::FtVtxDirAng2TimesJetE, lcfiplus::FtVtxDirAng1TimesJetE, lcfiplus::FtVtxDirAng12, lcfiplus::FtVtxDirAng2, lcfiplus::FtVtxDirAng1, lcfiplus::FtVtxSig12ByJetE, lcfiplus::FtVtxSig2ByJetE, lcfiplus::FtVtxSig1ByJetE, lcfiplus::FtVtxSig12, lcfiplus::FtVtxSig2, lcfiplus::FtVtxSig1, lcfiplus::FtVtxLen12ByJetE, lcfiplus::FtVtxLen2ByJetE, lcfiplus::FtVtxLen1ByJetE, lcfiplus::FtVtxLen12, lcfiplus::FtVtxLen2, lcfiplus::FtVtxLen1, lcfiplus::FtJetE, lcfiplus::FtNvtx, lcfiplus::Ft1VtxProb, lcfiplus::FtVtxLen12AllByJetE, lcfiplus::FtVtxLen12All, lcfiplus::FtVtxMassAll, lcfiplus::FtNvtxAll, lcfiplus::FtNtrk, lcfiplus::FtNtrkWithoutV0, lcfiplus::FtAuxiliaryM, and lcfiplus::FtAuxiliary.
Referenced by lcfiplus::FTManager::process().
processEvent()
virtual void lcfiplus::FTAlgo::processEvent () inline virtual
Reimplemented in lcfiplus::FtMCNC, and lcfiplus::FtMCNB.
Referenced by lcfiplus::FTManager::process().
setEvent()
void lcfiplus::FTAlgo::setEvent (const Event * event, const Vertex * privtx)
References _event, and _privtx.
Referenced by lcfiplus::FTManager::process().
setJet()
void lcfiplus::FTAlgo::setJet (const Jet * jet)
References _jet.
Referenced by lcfiplus::FTManager::process().
setNHitsJointProbD0()
void lcfiplus::FTAlgo::setNHitsJointProbD0 (int value)
References _nhitsJointProbD0.
Referenced by lcfiplus::FTManager::process().
setNHitsJointProbZ0()
void lcfiplus::FTAlgo::setNHitsJointProbZ0 (int value)
References _nhitsJointProbZ0.
Referenced by lcfiplus::FTManager::process().
setNHitsMostSignificantTrack()
void lcfiplus::FTAlgo::setNHitsMostSignificantTrack (int value)
References _nhitsMostSignificantTrack.
Referenced by lcfiplus::FTManager::process().
Member Data Documentation
_event
const Event* lcfiplus::FTAlgo::_event protected
Referenced by setEvent().
_jet
const Jet* lcfiplus::FTAlgo::_jet protected
Referenced by setJet().
_name
string lcfiplus::FTAlgo::_name protected
Referenced by getName().
_nhitsJointProbD0
int lcfiplus::FTAlgo::_nhitsJointProbD0 protected
Referenced by setNHitsJointProbD0().
_nhitsJointProbZ0
int lcfiplus::FTAlgo::_nhitsJointProbZ0 protected
Referenced by setNHitsJointProbZ0().
_nhitsMostSignificantTrack
int lcfiplus::FTAlgo::_nhitsMostSignificantTrack protected
Referenced by setNHitsMostSignificantTrack().
_privtx
const Vertex* lcfiplus::FTAlgo::_privtx protected
Referenced by setEvent().
_result
float lcfiplus::FTAlgo::_result protected
Referenced by getValue(), and getValueAddress().
The documentation for this class was generated from the following files:
flavtag.h
flavtag.cc