LCFIPlus: lcfiplus::FTManager Class Reference
lcfiplus::FTManager Class Reference
#include <flavtag.h>
Public Member Functions
void initVars ()
void fillTree ()
void openTree ()
void openFile (const char *filename)
void closeFile ()
void process (const Event *event, const Vertex *privtx, int nhitsJointProbD0, int nhitsJointProbZ0, int nhitsMostSignificantTrack, JetVec &jets)
float * getVarAddress (const string &varname)
void setEval (bool seteval, bool exportAllVars)
void addReader (TMVA::Reader *reader, const FlavtagCategory &c)
void setParamName (TString s)
const FtIPProbHolder * getIPProbHolder () const
void setIPProbHolder (FtIPProbHolder *holder)
double getAuxiliary () const
void setAuxiliary (double aux)
Static Public Member Functions
static FTManager & getInstance ()
Member Function Documentation
addReader()
void lcfiplus::FTManager::addReader (TMVA::Reader * reader, const FlavtagCategory & c)
Referenced by lcfiplus::ReadMVA::init().
closeFile()
void lcfiplus::FTManager::closeFile ()
Referenced by lcfiplus::MakeNtuple::end().
fillTree()
void lcfiplus::FTManager::fillTree ()
Referenced by process().
getAuxiliary()
double lcfiplus::FTManager::getAuxiliary () const inline
Referenced by lcfiplus::FtAuxiliaryM::process().
getInstance()
static FTManager& lcfiplus::FTManager::getInstance () inline static
Referenced by lcfiplus::MakeNtuple::end(), lcfiplus::MakeNtuple::init(), lcfiplus::ReadMVA::init(), lcfiplus::FlavorTag::init(), lcfiplus::FlavorTag::process(), lcfiplus::FtAuxiliaryM::process(), lcfiplus::FtJProbR2::process(), lcfiplus::FtJProbZ2::process(), lcfiplus::FtJProbR25Sigma::process(), lcfiplus::FtJProbZ25Sigma::process(), lcfiplus::FtD0bProb::process(), lcfiplus::FtD0bProb2::process(), lcfiplus::FtD0cProb::process(), lcfiplus::FtD0cProb2::process(), lcfiplus::FtD0qProb::process(), lcfiplus::FtD0qProb2::process(), lcfiplus::FtD0bProbSigned::process(), lcfiplus::FtD0cProbSigned::process(), lcfiplus::FtD0qProbSigned::process(), lcfiplus::FtD0bProbIP::process(), lcfiplus::FtD0cProbIP::process(), lcfiplus::FtZ0bProb::process(), lcfiplus::FtZ0bProb2::process(), lcfiplus::FtZ0cProb::process(), lcfiplus::FtZ0cProb2::process(), lcfiplus::FtZ0qProb::process(), lcfiplus::FtZ0qProb2::process(), lcfiplus::FtZ0bProbIP::process(), and lcfiplus::FtZ0cProbIP::process().
getIPProbHolder()
const FtIPProbHolder* lcfiplus::FTManager::getIPProbHolder () const inline
Referenced by lcfiplus::FtJProbR2::process(), lcfiplus::FtJProbZ2::process(), lcfiplus::FtJProbR25Sigma::process(), lcfiplus::FtJProbZ25Sigma::process(), lcfiplus::FtD0bProb::process(), lcfiplus::FtD0bProb2::process(), lcfiplus::FtD0cProb::process(), lcfiplus::FtD0cProb2::process(), lcfiplus::FtD0qProb::process(), lcfiplus::FtD0qProb2::process(), lcfiplus::FtD0bProbSigned::process(), lcfiplus::FtD0cProbSigned::process(), lcfiplus::FtD0qProbSigned::process(), lcfiplus::FtD0bProbIP::process(), lcfiplus::FtD0cProbIP::process(), lcfiplus::FtZ0bProb::process(), lcfiplus::FtZ0bProb2::process(), lcfiplus::FtZ0cProb::process(), lcfiplus::FtZ0cProb2::process(), lcfiplus::FtZ0qProb::process(), lcfiplus::FtZ0qProb2::process(), lcfiplus::FtZ0bProbIP::process(), and lcfiplus::FtZ0cProbIP::process().
getVarAddress()
float * lcfiplus::FTManager::getVarAddress (const string & varname)
References lcfiplus::FTAlgo::getName(), and lcfiplus::FTAlgo::getValueAddress().
Referenced by lcfiplus::ReadMVA::init().
initVars()
void lcfiplus::FTManager::initVars ()
Referenced by lcfiplus::FlavorTag::init().
openFile()
void lcfiplus::FTManager::openFile (const char * filename)
References lcfiplus::FTAlgo::getName(), and lcfiplus::FTAlgo::getValueAddress().
Referenced by lcfiplus::MakeNtuple::init().
openTree()
void lcfiplus::FTManager::openTree ()
References lcfiplus::FTAlgo::getName(), and lcfiplus::FTAlgo::getValueAddress().
Referenced by lcfiplus::ReadMVA::init().
process()
void lcfiplus::FTManager::process (const Event * event, const Vertex * privtx, int nhitsJointProbD0, int nhitsJointProbZ0, int nhitsMostSignificantTrack, JetVec & jets)
References lcfiplus::Parameters::add(), lcfiplus::Jet::addParam(), fillTree(), lcfiplus::FTAlgo::getName(), lcfiplus::FTAlgo::process(), lcfiplus::FTAlgo::processEvent(), lcfiplus::FTAlgo::setEvent(), lcfiplus::FTAlgo::setJet(), lcfiplus::FTAlgo::setNHitsJointProbD0(), lcfiplus::FTAlgo::setNHitsJointProbZ0(), and lcfiplus::FTAlgo::setNHitsMostSignificantTrack().
Referenced by lcfiplus::FlavorTag::process().
setAuxiliary()
void lcfiplus::FTManager::setAuxiliary (double aux) inline
Referenced by lcfiplus::FlavorTag::process().
setEval()
void lcfiplus::FTManager::setEval (bool seteval, bool exportAllVars) inline
Referenced by lcfiplus::ReadMVA::init().
setIPProbHolder()
void lcfiplus::FTManager::setIPProbHolder (FtIPProbHolder * holder) inline
Referenced by lcfiplus::FlavorTag::process().
setParamName()
void lcfiplus::FTManager::setParamName (TString s) inline
Referenced by lcfiplus::ReadMVA::init().
The documentation for this class was generated from the following files:
flavtag.h
FlavorTag.cc
flavtag.cc