LCFIPlus: lcfiplus::Parameters Class Reference
lcfiplus::Parameters Class Reference
#include <lcfiplus.h>
Public Member Functions
Parameters (bool as=true)
~Parameters ()
Parameters (const Parameters &ref)
Parameters & operator= (const Parameters &ref)
template<typename T >
void fetch (const char *key, T &ret, T def=T()) const
template<typename T >
void fetchArray (const char *key, vector< T > &ret) const
template<typename T >
T get (const char *key, T def=T()) const
template<typename T >
std::vector< T > getVec (const char *key) const
bool exist (const char *key) const
template<typename T >
void add (const char *key, T data)
void remove (const char *key)
void clear ()
template<typename T >
void assign (const char *key, T data)
const map< string, pair< const type_info *, void * > > & paramMap () const
Constructor & Destructor Documentation
Parameters() [1/2]
lcfiplus::Parameters::Parameters (bool as = true) inline
~Parameters()
lcfiplus::Parameters::~Parameters () inline
Parameters() [2/2]
lcfiplus::Parameters::Parameters (const Parameters & ref) inline
Member Function Documentation
add()
template<typename T > void lcfiplus::Parameters::add (const char * key, T data) inline
Referenced by LcfiplusProcessor::init(), operator=(), lcfiplus::JetClustering::process(), lcfiplus::FTManager::process(), and lcfiplus::LCIOStorer::ReadJets().
assign()
template<typename T > void lcfiplus::Parameters::assign (const char * key, T data) inline
clear()
void lcfiplus::Parameters::clear ()
Referenced by operator=().
exist()
bool lcfiplus::Parameters::exist (const char * key) const inline
fetch()
template<typename T > void lcfiplus::Parameters::fetch (const char * key, T & ret, T def = T()) const inline
fetchArray()
template<typename T > void lcfiplus::Parameters::fetchArray (const char * key, vector< T > & ret) const inline
Referenced by lcfiplus::TrainMVA::init(), lcfiplus::ReadMVA::init(), and lcfiplus::JetClustering::init().
get()
template<typename T > T lcfiplus::Parameters::get (const char * key, T def = T()) const inline
Referenced by lcfiplus::VertexMassRecovery::init(), lcfiplus::PrimaryVertexFinder::init(), lcfiplus::MakeROOTFileCC::init(), lcfiplus::MakeNtuple::init(), lcfiplus::VertexFindingwithDL::init(), lcfiplus::TrainMVA::init(), lcfiplus::VertexNtuple::init(), lcfiplus::TrackNtuple::init(), lcfiplus::ReadMVA::init(), lcfiplus::FlavorTag::init(), lcfiplus::BuildUpVertex::init(), lcfiplus::JetClustering::init(), lcfiplus::JetVertexRefiner::init(), lcfiplus::MakeROOTFileBB::init(), lcfiplus::ZHHAlgo::init(), lcfiplus::TestAlgo::init(), lcfiplus::VertexAnalysis::init(), lcfiplus::FlavtagReader::init(), lcfiplus::TestAlgoV0::init(), lcfiplus::ZHHAlgo::process(), lcfiplus::FlavtagReader::process(), lcfiplus::ZHHAlgo::sortBtag(), and lcfiplus::LCIOStorer::WritePID().
getVec()
template<typename T > std::vector<T> lcfiplus::Parameters::getVec (const char * key) const inline
operator=()
Parameters & lcfiplus::Parameters::operator= (const Parameters & ref)
References add(), and clear().
paramMap()
const map<string, pair<const type_info*, void*> >& lcfiplus::Parameters::paramMap () const inline
Referenced by lcfiplus::LCIOStorer::WritePID().
remove()
void lcfiplus::Parameters::remove (const char * key) inline
The documentation for this class was generated from the following files:
lcfiplus.h
lcfiplus.cc