LCFIPlus: lcfiplus::VertexFinderSuehara::SortTracksByIPSig Class Reference
lcfiplus::VertexFinderSuehara::SortTracksByIPSig Class Reference
#include <VertexFinderSuehara.h>
Public Member Functions
SortTracksByIPSig (Vertex *v)
bool operator() (const Track *p1, const Track *p2)
Public Attributes
Vertex * priVertex
Constructor & Destructor Documentation
SortTracksByIPSig()
lcfiplus::VertexFinderSuehara::SortTracksByIPSig::SortTracksByIPSig (Vertex * v) inline
Member Function Documentation
operator()()
bool lcfiplus::VertexFinderSuehara::SortTracksByIPSig::operator() (const Track * p1, const Track * p2) inline
References lcfiplus::tpar::d0d0, lcfiplus::Track::getCovMatrix(), lcfiplus::Track::getD0(), lcfiplus::Track::getZ0(), and lcfiplus::tpar::z0z0.
Member Data Documentation
priVertex
Vertex* lcfiplus::VertexFinderSuehara::SortTracksByIPSig::priVertex
The documentation for this class was generated from the following file:
VertexFinderSuehara.h