LCFIPlus: lcfiplus::FlavorTag Class Reference
lcfiplus::FlavorTag Class Reference
Controls the event data and registers and holds algorithms for the computation of flavor tagging variables.
#include <FlavorTag.h>
Public Member Functions
FlavorTag ()
virtual ~FlavorTag ()
void init (Parameters *param)
void process ()
void end ()
Public Member Functions inherited from lcfiplus::Algorithm
Algorithm ()
virtual ~Algorithm ()
Additional Inherited Members
Protected Member Functions inherited from lcfiplus::Algorithm
Parameters * GetParam () const
Detailed Description
Controls the event data and registers and holds algorithms for the computation of flavor tagging variables.
This algorithm must be included in the algorithm tag of the XML steering file when using any of the flavor tagging features, e.g. ntuple production, TMVA training, and evaluation.
Author
T. Tanabe, ICEPP, The University of Tokyo
Version
$Id$
Constructor & Destructor Documentation
FlavorTag()
lcfiplus::FlavorTag::FlavorTag () inline
~FlavorTag()
virtual lcfiplus::FlavorTag::~FlavorTag () inline virtual
Member Function Documentation
end()
void lcfiplus::FlavorTag::end () virtual
Reimplemented from lcfiplus::Algorithm.
init()
void lcfiplus::FlavorTag::init (Parameters * param) virtual
Reimplemented from lcfiplus::Algorithm.
References lcfiplus::Parameters::get(), lcfiplus::FTManager::getInstance(), lcfiplus::Algorithm::init(), lcfiplus::FTManager::initVars(), lcfiplus::Event::Instance(), and lcfiplus::Event::setDefaultPrimaryVertex().
process()
void lcfiplus::FlavorTag::process () virtual
Implements lcfiplus::Algorithm.
References lcfiplus::FTManager::getInstance(), lcfiplus::Event::Instance(), lcfiplus::FTManager::process(), lcfiplus::FTManager::setAuxiliary(), and lcfiplus::FTManager::setIPProbHolder().
The documentation for this class was generated from the following files:
FlavorTag.h
FlavorTag.cc