LCFIPlus: lcfiplus::Pi0VertexFinder Class Reference
lcfiplus::Pi0VertexFinder Class Reference
#include <Pi0VertexFinder.h>
Public Member Functions
Pi0VertexFinder ()
Pi0VertexFinder (vector< string > weightfiles, vector< string > booknames, vector< double > opp, string pi0pdfname, string pi0pdfname2d)
~Pi0VertexFinder ()
void Initialize ()
void Make_GammaVector (const lcfiplus::Neutral *ntrl)
void Reco_Pi0s (TVector3 vtx, TVector3 vtxdir)
TLorentzVector Corr_VtxVect (int vtxtype, TLorentzVector vtx1vect, int *npart, TVector3 vtx, TVector3 vtxdir)
int Get_nPi0 ()
Constructor & Destructor Documentation
Pi0VertexFinder() [1/2]
lcfiplus::Pi0VertexFinder::Pi0VertexFinder ()
Pi0VertexFinder() [2/2]
Pi0VertexFinder::Pi0VertexFinder (vector< string > weightfiles, vector< string > booknames, vector< double > opp, string pi0pdfname, string pi0pdfname2d)
~Pi0VertexFinder()
Pi0VertexFinder::~Pi0VertexFinder ()
Member Function Documentation
Corr_VtxVect()
TLorentzVector Pi0VertexFinder::Corr_VtxVect (int vtxtype, TLorentzVector vtx1vect, int * npart, TVector3 vtx, TVector3 vtxdir)
Referenced by lcfiplus::VertexMassRecovery::process().
Get_nPi0()
int Pi0VertexFinder::Get_nPi0 ()
Referenced by lcfiplus::VertexMassRecovery::process().
Initialize()
void Pi0VertexFinder::Initialize ()
Referenced by lcfiplus::VertexMassRecovery::process().
Make_GammaVector()
void Pi0VertexFinder::Make_GammaVector (const lcfiplus::Neutral * ntrl)
References lcfiplus::tpar::ecal, lcfiplus::Neutral::getClusters(), and lcfiplus::tpar::hcal.
Referenced by lcfiplus::VertexMassRecovery::process().
Reco_Pi0s()
void Pi0VertexFinder::Reco_Pi0s (TVector3 vtx, TVector3 vtxdir)
Referenced by lcfiplus::VertexMassRecovery::process().
The documentation for this class was generated from the following files:
Pi0VertexFinder.h
Pi0VertexFinder.cc