LCFIPlus: lcfiplus::PrimaryVertexFinder Class Reference
lcfiplus::PrimaryVertexFinder Class Reference
#include <process.h>
Public Member Functions
PrimaryVertexFinder ()
virtual ~PrimaryVertexFinder ()
void init (Parameters *param)
void process ()
void end ()
ClassDef (PrimaryVertexFinder, 1)
Public Member Functions inherited from lcfiplus::Algorithm
Algorithm ()
virtual ~Algorithm ()
Additional Inherited Members
Protected Member Functions inherited from lcfiplus::Algorithm
Parameters * GetParam () const
Constructor & Destructor Documentation
PrimaryVertexFinder()
lcfiplus::PrimaryVertexFinder::PrimaryVertexFinder () inline
~PrimaryVertexFinder()
virtual lcfiplus::PrimaryVertexFinder::~PrimaryVertexFinder () inline virtual
Member Function Documentation
ClassDef()
lcfiplus::PrimaryVertexFinder::ClassDef (PrimaryVertexFinder , 1)
end()
void lcfiplus::PrimaryVertexFinder::end () virtual
Reimplemented from lcfiplus::Algorithm.
init()
void lcfiplus::PrimaryVertexFinder::init (Parameters * param) virtual
Reimplemented from lcfiplus::Algorithm.
References lcfiplus::Parameters::get(), lcfiplus::Algorithm::init(), lcfiplus::Event::Instance(), lcfiplus::TrackSelectorConfig::maxD0, lcfiplus::EventStore::PERSIST, lcfiplus::EventStore::Register(), and lcfiplus::Event::setDefaultPrimaryVertex().
process()
void lcfiplus::PrimaryVertexFinder::process () virtual
Implements lcfiplus::Algorithm.
References lcfiplus::findPrimaryVertex(), lcfiplus::Vertex::getTracks(), lcfiplus::Event::Instance(), and lcfiplus::verbose.
The documentation for this class was generated from the following files:
process.h
process.cc