LCFIPlus: lcfiplus::VertexAnalysis Class Reference
lcfiplus::VertexAnalysis Class Reference
#include <testproc.h>
Public Member Functions
VertexAnalysis ()
virtual ~VertexAnalysis ()
void init (Parameters *param)
void process ()
void end ()
ClassDef (VertexAnalysis, 1)
Public Member Functions inherited from lcfiplus::Algorithm
Algorithm ()
virtual ~Algorithm ()
Additional Inherited Members
Protected Member Functions inherited from lcfiplus::Algorithm
Parameters * GetParam () const
Constructor & Destructor Documentation
VertexAnalysis()
lcfiplus::VertexAnalysis::VertexAnalysis () inline
~VertexAnalysis()
virtual lcfiplus::VertexAnalysis::~VertexAnalysis () inline virtual
Member Function Documentation
ClassDef()
lcfiplus::VertexAnalysis::ClassDef (VertexAnalysis , 1)
end()
void lcfiplus::VertexAnalysis::end () virtual
Reimplemented from lcfiplus::Algorithm.
init()
void lcfiplus::VertexAnalysis::init (Parameters * param) virtual
Reimplemented from lcfiplus::Algorithm.
References lcfiplus::Parameters::get(), and lcfiplus::Algorithm::init().
process()
void lcfiplus::VertexAnalysis::process () virtual
Implements lcfiplus::Algorithm.
References lcfiplus::tpar::d0, lcfiplus::tpar::d0d0, lcfiplus::EventStore::Get(), lcfiplus::Track::getChi2(), lcfiplus::Track::getCovMatrix(), lcfiplus::Track::getD0(), lcfiplus::Track::getFtdHits(), lcfiplus::Track::getMcp(), lcfiplus::Event::getMCParticles(), lcfiplus::Track::getNdf(), lcfiplus::Event::getPrimaryVertex(), lcfiplus::MCParticle::getSemiStableBParent(), lcfiplus::MCParticle::getSemiStableCParent(), lcfiplus::MCParticle::getSemiStableParent(), lcfiplus::Event::getTracks(), lcfiplus::Vertex::getTracks(), lcfiplus::Track::getVtxHits(), lcfiplus::Track::getZ0(), lcfiplus::Event::Instance(), lcfiplus::tpar::z0, and lcfiplus::tpar::z0z0.
The documentation for this class was generated from the following files:
testproc.h
testproc.cc