LCFIPlus: lcfiplus::EventStore Class Reference
lcfiplus::EventStore Class Reference
A simple named storage for event data.
#include <EventStore.h>
Classes
struct StoredEntry
Public Types
enum { DO_NOT_DELETE = 0x0001, PERSIST = 0x0002, JET_WRITE_VERTEX = 0x1000 }
Public Member Functions
void RegisterObserver (EventStoreObserver *observer)
void UnregisterObserver (EventStoreObserver *observer)
int Count (const char *name) const
bool IsExist (const char *name) const
bool IsExist (const char *name, const char *classname) const
const char * GetClassName (const char *name, int idx=0) const
void * GetObject (const char *name, const char *classname="") const
template<typename T >
bool Get (const char *name, const vector< const T *> *&buf) const
template<typename T >
bool Get (const char *name, const vector< T *> *&buf) const
template<typename T >
bool Get (const char *name, const vector< T > *&buf) const
template<typename T >
bool Get (const char *name, const T *&buf) const
void * RegisterObject (const char *name, const char *classname, int flags=0)
template<typename T >
bool Register (const char *name, vector< T *> *&buf, int flags=0)
template<typename T >
bool Register (const char *name, vector< T > *&buf, int flags=0)
template<typename T >
bool Register (const char *name, T *&buf, int flags=0)
void Print () const
void ClearObjects ()
virtual ~EventStore ()
const multimap< string, lcfiplus::EventStore::StoredEntry > & GetObjectMap () const
Protected Member Functions
void *const & GetObjectRef (const char *name, const char *classname="") const
EventStore ()
Detailed Description
A simple named storage for event data.
To obtain data: use Get(name) (in compiled code) or GetObject(name) (in CINT)
CAUTION: GetObject() does not have type-check.
To register data: use Register(name) or RegisterObject(name, class) Use a pointer returned (cannot register a pointer from the caller). Any classes or vector of classes with ClassDef() can be registered.
Author
T. Suehara, ICEPP, The University of Tokyo
Version
$Id$
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
DO_NOT_DELETE
PERSIST
JET_WRITE_VERTEX
Constructor & Destructor Documentation
~EventStore()
lcfiplus::EventStore::~EventStore () virtual
EventStore()
lcfiplus::EventStore::EventStore () protected
Member Function Documentation
ClearObjects()
void lcfiplus::EventStore::ClearObjects ()
References lcfiplus::EventStore::StoredEntry::classname, lcfiplus::EventStore::StoredEntry::flag, and lcfiplus::EventStore::StoredEntry::obj.
Count()
int lcfiplus::EventStore::Count (const char * name) const
Get() [1/4]
template<typename T > bool lcfiplus::EventStore::Get (const char * name, const vector< const T *> *& buf) const
Referenced by lcfiplus::JetClustering::init(), lcfiplus::BuildUpVertex::process(), lcfiplus::JetClustering::process(), lcfiplus::ZHHAlgo::process(), lcfiplus::TestAlgo::process(), lcfiplus::VertexAnalysis::process(), lcfiplus::FlavtagReader::process(), and lcfiplus::TestAlgoV0::process().
Get() [2/4]
template<typename T > bool lcfiplus::EventStore::Get (const char * name, const vector< T *> *& buf) const
Get() [3/4]
template<typename T > bool lcfiplus::EventStore::Get (const char * name, const vector< T > *& buf) const
Get() [4/4]
template<typename T > bool lcfiplus::EventStore::Get (const char * name, const T *& buf) const
GetClassName()
const char * lcfiplus::EventStore::GetClassName (const char * name, int idx = 0) const
Referenced by lcfiplus::TreeStorer::Register().
GetObject()
void * lcfiplus::EventStore::GetObject (const char * name, const char * classname = "") const
Referenced by lcfiplus::Event::getPrimaryVertex(), and lcfiplus::TreeStorer::Register().
GetObjectMap()
const multimap<string, lcfiplus::EventStore::StoredEntry >& lcfiplus::EventStore::GetObjectMap () const inline
Referenced by lcfiplus::LCIOStorer::AutoConvert().
GetObjectRef()
void *const & lcfiplus::EventStore::GetObjectRef (const char * name, const char * classname = "") const protected
Referenced by lcfiplus::Event::getJets(), lcfiplus::Event::getMCColorSinglets(), lcfiplus::Event::getMCParticles(), lcfiplus::Event::getNeutrals(), lcfiplus::Event::getSecondaryVertices(), and lcfiplus::Event::getTracks().
IsExist() [1/2]
bool lcfiplus::EventStore::IsExist (const char * name) const inline
IsExist() [2/2]
bool lcfiplus::EventStore::IsExist (const char * name, const char * classname) const
Print()
void lcfiplus::EventStore::Print () const
Register() [1/3]
template<typename T > bool lcfiplus::EventStore::Register (const char * name, vector< T *> *& buf, int flags = 0)
Referenced by lcfiplus::VertexMassRecovery::init(), lcfiplus::PrimaryVertexFinder::init(), lcfiplus::VertexFindingwithDL::init(), lcfiplus::BuildUpVertex::init(), lcfiplus::JetClustering::init(), and lcfiplus::JetVertexRefiner::init().
Register() [2/3]
template<typename T > bool lcfiplus::EventStore::Register (const char * name, vector< T > *& buf, int flags = 0)
Register() [3/3]
template<typename T > bool lcfiplus::EventStore::Register (const char * name, T *& buf, int flags = 0)
RegisterObject()
void * lcfiplus::EventStore::RegisterObject (const char * name, const char * classname, int flags = 0)
Referenced by lcfiplus::TreeStorer::Register().
RegisterObserver()
void lcfiplus::EventStore::RegisterObserver (EventStoreObserver * observer) inline
UnregisterObserver()
void lcfiplus::EventStore::UnregisterObserver (EventStoreObserver * observer) inline
The documentation for this class was generated from the following files:
EventStore.h
EventStore.cc