LCFIPlus: lcfiplus::ReadMVA Class Reference
lcfiplus::ReadMVA Class Reference
Lcfiplus algorithm for reading training data from TMVA.
#include <ReadMVA.h>
Public Member Functions
ReadMVA ()
~ReadMVA ()
void init (Parameters *param)
void process ()
void end ()
Public Member Functions inherited from lcfiplus::Algorithm
Algorithm ()
virtual ~Algorithm ()
Protected Member Functions
ClassDef (ReadMVA, 1)
Protected Member Functions inherited from lcfiplus::Algorithm
Parameters * GetParam () const
Protected Attributes
bool _verbose
TString _inputFileB
TString _inputFileC
TString _inputFileO
TString _treeNameB
TString _treeNameC
TString _treeNameO
TString _cutB
TString _cutC
TString _cutO
TString _outputDirectory
TString _outputPrefix
TString _treeName
TMVA::Types::EMVA _tmvaBookType
TString _tmvaBookName
TString _tmvaBookOptions
vector< FlavtagCategory > _categories
vector< TMVA::Reader * > _readers
Detailed Description
Lcfiplus algorithm for reading training data from TMVA.
Author
T. Tanabe, ICEPP, The University of Tokyo
Version
$Id$
Constructor & Destructor Documentation
ReadMVA()
lcfiplus::ReadMVA::ReadMVA () inline
~ReadMVA()
lcfiplus::ReadMVA::~ReadMVA () inline
Member Function Documentation
ClassDef()
lcfiplus::ReadMVA::ClassDef (ReadMVA , 1) protected
end()
void ReadMVA::end () virtual
Reimplemented from lcfiplus::Algorithm.
init()
void ReadMVA::init (Parameters * param) virtual
Reimplemented from lcfiplus::Algorithm.
References lcfiplus::FTManager::addReader(), lcfiplus::FlavtagCategory::definition, lcfiplus::Parameters::fetchArray(), lcfiplus::Parameters::get(), lcfiplus::FTManager::getInstance(), lcfiplus::FTManager::getVarAddress(), lcfiplus::Algorithm::init(), lcfiplus::FTManager::openTree(), lcfiplus::FlavtagCategory::preselection, lcfiplus::FTManager::setEval(), lcfiplus::FTManager::setParamName(), lcfiplus::FlavtagCategory::spec, and lcfiplus::FlavtagCategory::vars.
process()
void ReadMVA::process () virtual
Implements lcfiplus::Algorithm.
Member Data Documentation
_categories
vector<FlavtagCategory> lcfiplus::ReadMVA::_categories protected
_cutB
TString lcfiplus::ReadMVA::_cutB protected
_cutC
TString lcfiplus::ReadMVA::_cutC protected
_cutO
TString lcfiplus::ReadMVA::_cutO protected
_inputFileB
TString lcfiplus::ReadMVA::_inputFileB protected
_inputFileC
TString lcfiplus::ReadMVA::_inputFileC protected
_inputFileO
TString lcfiplus::ReadMVA::_inputFileO protected
_outputDirectory
TString lcfiplus::ReadMVA::_outputDirectory protected
_outputPrefix
TString lcfiplus::ReadMVA::_outputPrefix protected
_readers
vector<TMVA::Reader*> lcfiplus::ReadMVA::_readers protected
_tmvaBookName
TString lcfiplus::ReadMVA::_tmvaBookName protected
_tmvaBookOptions
TString lcfiplus::ReadMVA::_tmvaBookOptions protected
_tmvaBookType
TMVA::Types::EMVA lcfiplus::ReadMVA::_tmvaBookType protected
_treeName
TString lcfiplus::ReadMVA::_treeName protected
_treeNameB
TString lcfiplus::ReadMVA::_treeNameB protected
_treeNameC
TString lcfiplus::ReadMVA::_treeNameC protected
_treeNameO
TString lcfiplus::ReadMVA::_treeNameO protected
_verbose
bool lcfiplus::ReadMVA::_verbose protected
The documentation for this class was generated from the following files:
ReadMVA.h
ReadMVA.cc