LCFIPlus: lcfiplus::TrackPocaXY Class Reference
lcfiplus::TrackPocaXY Class Reference
#include <lcfiplus.h>
Public Member Functions
TrackPocaXY (const Track *trk, const Vertex *vtx)
TrackPocaXY (const Track *trk, const TVector3 &v)
bool success ()
double getFlightLength ()
double getPoca ()
double operator() (double *flt) const
Constructor & Destructor Documentation
TrackPocaXY() [1/2]
lcfiplus::TrackPocaXY::TrackPocaXY (const Track * trk, const Vertex * vtx)
TrackPocaXY() [2/2]
lcfiplus::TrackPocaXY::TrackPocaXY (const Track * trk, const TVector3 & v)
Member Function Documentation
getFlightLength()
double lcfiplus::TrackPocaXY::getFlightLength () inline
Referenced by lcfiplus::algoSigProb::signedD0(), lcfiplus::algoSigProb::signedD0Significance(), lcfiplus::algoSigProb::signedZ0(), lcfiplus::algoSigProb::trackD0Significance(), and lcfiplus::algoSigProb::trackZ0Significance().
getPoca()
double lcfiplus::TrackPocaXY::getPoca () inline
operator()()
double lcfiplus::TrackPocaXY::operator() (double * flt) const
References lcfiplus::tpar::d0, lcfiplus::Track::getD0(), lcfiplus::Track::getOmega(), lcfiplus::Track::getPhi(), lcfiplus::tpar::om, and lcfiplus::tpar::ph.
success()
bool lcfiplus::TrackPocaXY::success () inline
The documentation for this class was generated from the following files:
lcfiplus.h
lcfiplus.cc