LCFIPlus: lcfiplus::LCIOStorer Class Reference
lcfiplus::LCIOStorer Class Reference
#include <LCIOStorer.h>
Public Member Functions
LCIOStorer (const char *inputfile=NULL, const char *outputfile=NULL, bool autoread=true, bool autowrite=false, const char *outPrefix=0)
virtual ~LCIOStorer ()
bool Next (bool autovertex=false, bool autojet=false)
void SetEvent (lcio::LCEvent *event)
void SetColorSinglets (vector< MCParticle *> &mcps, vector< MCColorSinglet *> &mccs)
void InitMCPPFOCollections (const char *pfoColName, const char *mcColName, const char *mcpfoColName)
void InitPFOCollections (const char *pfoColName)
void InitVertexCollection (const char *lcioName, const char *flavtagName, bool readnow=true)
void InitJetCollection (const char *lcioName, const char *flavtagName, bool readnow=true, bool readvtx=true, const char *vtxname=0)
void ReadVertices (const char *vtxname, vector< const Vertex *> *lcficol)
void ReadJets (const char *jetname, vector< const Jet *> *lcficol, const char *vtxrelname=0)
void WriteVertices (const char *vertexName, const char *outName=0, const char *outRPName=0)
void WriteVertices (VertexVec *pvvtx, const char *newName, const char *newRPName=0)
void WriteJets (const char *jetName, const char *outName=0, bool writeVertex=true, const char *vtxName=0, const char *relName=0)
void WritePID (lcio::LCCollection *lciocol, lcio::ReconstructedParticle *lciojet, const lcfiplus::Jet *lcfijet, const char *paramname)
void WriteAllPIDs (lcio::LCCollection *lciocol, lcio::ReconstructedParticle *lciojet, const lcfiplus::Jet *lcfijet)
void WriteEvent ()
void AutoConvert ()
void setReadSubdetectorEnergies (bool flag)
void setTrackHitOrdering (int flag)
void setUpdateVertexRPDaughters (bool flag)
void setIgnoreLackOfVertexRP (bool flag)
void setParticleIDAlgorithmName (const char *algoName)
bool getReadSubdetectorEnergies () const
int getTrackHitOrdering () const
bool getUpdateVertexRPDaughters () const
bool getIgnoreLackOfVertexRP () const
const char * getParticleIDAlgorithmName ()
virtual void GetCallback (const char *name, const char *classname)
Public Member Functions inherited from lcfiplus::EventStoreObserver
EventStoreObserver ()
virtual ~EventStoreObserver ()
virtual void RegisterCallback (const char *, const char *, int)
Static Public Member Functions
static bool energy_sort_pfo (lcio::ReconstructedParticle *a, lcio::ReconstructedParticle *b)
Constructor & Destructor Documentation
LCIOStorer()
lcfiplus::LCIOStorer::LCIOStorer (const char * inputfile = NULL, const char * outputfile = NULL, bool autoread = true, bool autowrite = false, const char * outPrefix = 0)
~LCIOStorer()
lcfiplus::LCIOStorer::~LCIOStorer () virtual
Member Function Documentation
AutoConvert()
void lcfiplus::LCIOStorer::AutoConvert ()
References lcfiplus::EventStore::GetObjectMap().
energy_sort_pfo()
bool lcfiplus::LCIOStorer::energy_sort_pfo (lcio::ReconstructedParticle * a, lcio::ReconstructedParticle * b) static
GetCallback()
void LCIOStorer::GetCallback (const char * name, const char * classname) virtual
Reimplemented from lcfiplus::EventStoreObserver.
getIgnoreLackOfVertexRP()
bool lcfiplus::LCIOStorer::getIgnoreLackOfVertexRP () const inline
Referenced by LcfiplusProcessor::init().
getParticleIDAlgorithmName()
const char* lcfiplus::LCIOStorer::getParticleIDAlgorithmName () inline
getReadSubdetectorEnergies()
bool lcfiplus::LCIOStorer::getReadSubdetectorEnergies () const inline
Referenced by LcfiplusProcessor::init().
getTrackHitOrdering()
int lcfiplus::LCIOStorer::getTrackHitOrdering () const inline
Referenced by LcfiplusProcessor::init().
getUpdateVertexRPDaughters()
bool lcfiplus::LCIOStorer::getUpdateVertexRPDaughters () const inline
Referenced by LcfiplusProcessor::init().
InitJetCollection()
void lcfiplus::LCIOStorer::InitJetCollection (const char * lcioName, const char * flavtagName, bool readnow = true, bool readvtx = true, const char * vtxname = 0)
References lcfiplus::constVector().
Referenced by testSuehara().
InitMCPPFOCollections()
void lcfiplus::LCIOStorer::InitMCPPFOCollections (const char * pfoColName, const char * mcColName, const char * mcpfoColName)
Referenced by LcfiplusProcessor::init().
InitPFOCollections()
void lcfiplus::LCIOStorer::InitPFOCollections (const char * pfoColName)
Referenced by LcfiplusProcessor::init().
InitVertexCollection()
void lcfiplus::LCIOStorer::InitVertexCollection (const char * lcioName, const char * flavtagName, bool readnow = true)
References lcfiplus::constVector().
Referenced by testSuehara().
Next()
bool lcfiplus::LCIOStorer::Next (bool autovertex = false, bool autojet = false)
Referenced by lcfiplus::EventNavigator::EventNavigator(), lcfiplus::EventNavigator::Fwd(), testSuehara(), and testTomohiko().
ReadJets()
void lcfiplus::LCIOStorer::ReadJets (const char * jetname, vector< const Jet *> * lcficol, const char * vtxrelname = 0)
References lcfiplus::Parameters::add(), lcfiplus::Jet::add(), lcfiplus::Jet::addParam(), and lcfiplus::Jet::setId().
ReadVertices()
void lcfiplus::LCIOStorer::ReadVertices (const char * vtxname, vector< const Vertex *> * lcficol)
References lcfiplus::Vertex::add(), lcfiplus::Vertex::setId(), and lcfiplus::Vertex::setVertexingName().
SetColorSinglets()
void LCIOStorer::SetColorSinglets (vector< MCParticle *> & mcps, vector< MCColorSinglet *> & mccs)
References lcfiplus::MCColorSinglet::_finalcolorsinglets, lcfiplus::MCColorSinglet::_finalstrings, lcfiplus::MCColorSinglet::_initials, lcfiplus::MCColorSinglet::_mcp, lcfiplus::MCColorSinglet::_qqgluons, lcfiplus::MCColorSinglet::_realparticles, lcfiplus::constVector(), lcfiplus::MCParticle::getColorSinglet(), lcfiplus::MCParticle::getDaughters(), lcfiplus::MCParticle::getParent(), lcfiplus::MCParticle::getPDG(), and lcfiplus::MCParticle::isParent().
SetEvent()
void lcfiplus::LCIOStorer::SetEvent (lcio::LCEvent * event)
References lcfiplus::MCParticle::addDaughter(), lcfiplus::tpar::covN, lcfiplus::tpar::d0, lcfiplus::tpar::ETD, lcfiplus::tpar::FTD, lcfiplus::tpar::hitN, lcfiplus::tpar::om, lcfiplus::tpar::parN, lcfiplus::tpar::ph, lcfiplus::tpar::SET, lcfiplus::Neutral::setCaloEdep(), lcfiplus::Neutral::setClusters(), lcfiplus::Track::setId(), lcfiplus::Neutral::setId(), lcfiplus::Neutral::setMcp(), lcfiplus::MCParticle::setParent(), lcfiplus::Neutral::setPDG(), lcfiplus::Neutral::setV0(), lcfiplus::tpar::SIT, lcfiplus::tpar::td, lcfiplus::tpar::TPC, lcfiplus::tpar::VTX, and lcfiplus::tpar::z0.
setIgnoreLackOfVertexRP()
void lcfiplus::LCIOStorer::setIgnoreLackOfVertexRP (bool flag) inline
Referenced by LcfiplusProcessor::init().
setParticleIDAlgorithmName()
void lcfiplus::LCIOStorer::setParticleIDAlgorithmName (const char * algoName) inline
Referenced by LcfiplusProcessor::init().
setReadSubdetectorEnergies()
void lcfiplus::LCIOStorer::setReadSubdetectorEnergies (bool flag) inline
Referenced by LcfiplusProcessor::init().
setTrackHitOrdering()
void lcfiplus::LCIOStorer::setTrackHitOrdering (int flag) inline
Referenced by LcfiplusProcessor::init().
setUpdateVertexRPDaughters()
void lcfiplus::LCIOStorer::setUpdateVertexRPDaughters (bool flag) inline
Referenced by LcfiplusProcessor::init().
WriteAllPIDs()
void LCIOStorer::WriteAllPIDs (lcio::LCCollection * lciocol, lcio::ReconstructedParticle * lciojet, const lcfiplus::Jet * lcfijet)
References lcfiplus::Jet::params().
WriteEvent()
void lcfiplus::LCIOStorer::WriteEvent ()
WriteJets()
void lcfiplus::LCIOStorer::WriteJets (const char * jetName, const char * outName = 0, bool writeVertex = true, const char * vtxName = 0, const char * relName = 0)
References lcfiplus::Track::getCharge(), lcfiplus::Jet::getNeutrals(), lcfiplus::Vertex::getTracks(), lcfiplus::Jet::getTracks(), lcfiplus::Jet::getVertices(), and lcfiplus::Jet::setId().
WritePID()
void LCIOStorer::WritePID (lcio::LCCollection * lciocol, lcio::ReconstructedParticle * lciojet, const lcfiplus::Jet * lcfijet, const char * paramname)
References lcfiplus::Parameters::get(), lcfiplus::Jet::getParam(), and lcfiplus::Parameters::paramMap().
WriteVertices() [1/2]
void lcfiplus::LCIOStorer::WriteVertices (const char * vertexName, const char * outName = 0, const char * outRPName = 0)
WriteVertices() [2/2]
void lcfiplus::LCIOStorer::WriteVertices (VertexVec * pvvtx, const char * newName, const char * newRPName = 0)
References lcfiplus::Track::getCharge(), and lcfiplus::Vertex::setId().
The documentation for this class was generated from the following files:
LCIOStorer.h
LCIOStorer.cc