LCFIPlus: lcfiplus::MCVertex Class Reference
lcfiplus::MCVertex Class Reference
#include <lcfiplus.h>
Public Member Functions
MCVertex ()
void setParent (const MCParticle *parent)
const MCParticle * getParent () const
void add (const MCParticle *mcp)
void add (const Track *trk)
void setRecoVertex (const Vertex *vtx)
const vector< const MCParticle * > & getDaughters () const
const vector< const Track * > & getRecoTracks () const
const Vertex * getRecoVertex () const
const TVector3 & getPos () const
void setPos (const TVector3 &pos)
Constructor & Destructor Documentation
MCVertex()
lcfiplus::MCVertex::MCVertex () inline
Member Function Documentation
add() [1/2]
void lcfiplus::MCVertex::add (const MCParticle * mcp) inline
Referenced by findMcVertex(), lcfiplus::VertexFinderPerfect::findPerfectVertices(), and matchMcVertex().
add() [2/2]
void lcfiplus::MCVertex::add (const Track * trk) inline
getDaughters()
const vector<const MCParticle*>& lcfiplus::MCVertex::getDaughters () const inline
Referenced by findMcVertex(), matchMcVertex(), and matchMcVertexJet().
getParent()
const MCParticle* lcfiplus::MCVertex::getParent () const inline
Referenced by findMcVertex(), matchMcVertex(), and matchMcVertexRecoV0().
getPos()
const TVector3& lcfiplus::MCVertex::getPos () const inline
getRecoTracks()
const vector<const Track*>& lcfiplus::MCVertex::getRecoTracks () const inline
Referenced by matchMcVertexReco().
getRecoVertex()
const Vertex* lcfiplus::MCVertex::getRecoVertex () const inline
Referenced by matchMcVertexReco().
setParent()
void lcfiplus::MCVertex::setParent (const MCParticle * parent) inline
Referenced by findMcVertex(), and lcfiplus::VertexFinderPerfect::findPerfectVertices().
setPos()
void lcfiplus::MCVertex::setPos (const TVector3 & pos) inline
Referenced by lcfiplus::VertexFinderPerfect::findPerfectVertices().
setRecoVertex()
void lcfiplus::MCVertex::setRecoVertex (const Vertex * vtx) inline
Referenced by matchMcVertexReco().
The documentation for this class was generated from the following file:
lcfiplus.h