LCFIPlus: lcfiplus::Track Class Reference
lcfiplus::Track Class Reference
#include <lcfiplus.h>
Public Member Functions
~Track ()
int getId () const
void setId (int id)
const lcfiplus::MCParticle * getMcp () const
void setMcp (const lcfiplus::MCParticle *mcp)
int getPDG () const
void setPDG (int pdg)
double getCharge () const
void setCharge (double charge)
double getD0 () const
double getZ0 () const
double getPhi () const
double getOmega () const
double getTanLambda () const
void setHelix (double d0, double z0, double phi, double omega, double tanLambda)
void setHelix (double *par)
const double * getCovMatrix () const
void setCovMatrix (double *cov)
int getVtxHits () const
int getFtdHits () const
int getSitHits () const
int getTpcHits () const
int getSetHits () const
int getEtdHits () const
void setTrackHits (int *hits)
const double * getCaloEdep () const
void setCaloEdep (double *calo)
double getRadiusOfInnermostHit () const
void setRadiusOfInnermostHit (double rimh)
double getChi2 () const
void setChi2 (double chi2)
int getNdf () const
void setNdf (int ndf)
void setFlightLength (double flt) const
double getFlightLength () const
void setParticleIDProbability (string parName, double pidProbability)
double getParticleIDProbability (const char *parName) const
void setCorrEnergy (double mass)
double getCorrEnergy () const
void swapEnergy ()
void setBNess (double bness)
double getBNess () const
double getCNess () const
void setCNess (double cness)
double getX () const
double getY () const
double getZ () const
TVector3 getPos () const
TVector3 momentumAtVertex (const Vertex *vtx) const
Constructor & Destructor Documentation
~Track()
lcfiplus::Track::~Track () inline
Member Function Documentation
getBNess()
double lcfiplus::Track::getBNess () const inline
getCaloEdep()
const double* lcfiplus::Track::getCaloEdep () const inline
Referenced by lcfiplus::algoEtc::SimpleSecElectronFinder(), and lcfiplus::algoEtc::SimpleSecMuonFinder().
getCharge()
double lcfiplus::Track::getCharge () const inline
Referenced by lcfiplus::EventNavigator::drawEvent(), lcfiplus::VertexFinderwithDL::GetPairsEncoderDecoderTracks(), lcfiplus::Helix::Helix(), lcfiplus::MakeROOTFileCC::process(), lcfiplus::MakeROOTFileBB::process(), lcfiplus::LCIOStorer::WriteJets(), and lcfiplus::LCIOStorer::WriteVertices().
getChi2()
double lcfiplus::Track::getChi2 () const inline
Referenced by lcfiplus::TestAlgo::process(), and lcfiplus::VertexAnalysis::process().
getCNess()
double lcfiplus::Track::getCNess () const inline
getCorrEnergy()
double lcfiplus::Track::getCorrEnergy () const inline
getCovMatrix()
const double* lcfiplus::Track::getCovMatrix () const inline
Referenced by lcfiplus::VertexFinderwithDL::GetPairsEncoderDecoderTracks(), lcfiplus::Helix::Helix(), KalTrk::KalTrk(), lcfiplus::VertexFinderSuehara::SortTracksByIPSig::operator()(), lcfiplus::TrackSelector::passesCut(), lcfiplus::MakeROOTFileCC::process(), lcfiplus::MakeROOTFileBB::process(), lcfiplus::TestAlgo::process(), lcfiplus::VertexAnalysis::process(), lcfiplus::algoSigProb::signedD0Significance(), lcfiplus::algoSigProb::signedZ0Significance(), lcfiplus::algoEtc::SimpleSecElectronFinder(), lcfiplus::algoEtc::SimpleSecMuonFinder(), testSuehara(), lcfiplus::algoSigProb::trackD0Significance(), and lcfiplus::algoSigProb::trackZ0Significance().
getD0()
double lcfiplus::Track::getD0 () const inline
References lcfiplus::tpar::d0.
Referenced by lcfiplus::EventNavigator::drawEvent(), lcfiplus::VertexFinderwithDL::GetPairsEncoderDecoderTracks(), lcfiplus::Helix::Helix(), KalTrk::KalTrk(), lcfiplus::VertexFinderSuehara::SortTracksByIPSig::operator()(), lcfiplus::TrackPocaXY::operator()(), lcfiplus::TrackSelector::passesCut(), lcfiplus::MakeROOTFileCC::process(), lcfiplus::MakeROOTFileBB::process(), lcfiplus::TestAlgo::process(), lcfiplus::VertexAnalysis::process(), lcfiplus::algoSigProb::signedD0(), lcfiplus::algoSigProb::signedD0Significance(), lcfiplus::algoSigProb::signedZ0(), lcfiplus::algoEtc::SimpleSecElectronFinder(), lcfiplus::algoEtc::SimpleSecMuonFinder(), and testSuehara().
getEtdHits()
int lcfiplus::Track::getEtdHits () const inline
References lcfiplus::tpar::ETD.
getFlightLength()
double lcfiplus::Track::getFlightLength () const inline
getFtdHits()
int lcfiplus::Track::getFtdHits () const inline
References lcfiplus::tpar::FTD.
Referenced by lcfiplus::TrackSelector::passesCut(), lcfiplus::VertexAnalysis::process(), and lcfiplus::algoSigProb::trackSelectionForFlavorTag().
getId()
int lcfiplus::Track::getId () const inline
Referenced by testSuehara().
getMcp()
const lcfiplus::MCParticle* lcfiplus::Track::getMcp () const inline
Referenced by lcfiplus::Event::getMCParticle(), lcfiplus::Vertex::Print(), lcfiplus::VertexAnalysis::process(), lcfiplus::TestAlgoV0::process(), and testSuehara().
getNdf()
int lcfiplus::Track::getNdf () const inline
Referenced by lcfiplus::VertexAnalysis::process().
getOmega()
double lcfiplus::Track::getOmega () const inline
References lcfiplus::tpar::om.
Referenced by lcfiplus::VertexFinderwithDL::GetPairsEncoderDecoderTracks(), lcfiplus::Helix::Helix(), KalTrk::KalTrk(), lcfiplus::TrackPocaXY::operator()(), lcfiplus::MakeROOTFileCC::process(), and lcfiplus::MakeROOTFileBB::process().
getParticleIDProbability()
double lcfiplus::Track::getParticleIDProbability (const char * parName) const inline
Referenced by lcfiplus::JetFinder::prerun().
getPDG()
int lcfiplus::Track::getPDG () const inline
Referenced by lcfiplus::EventNavigator::drawEvent().
getPhi()
double lcfiplus::Track::getPhi () const inline
References lcfiplus::tpar::ph.
Referenced by lcfiplus::EventNavigator::drawEvent(), lcfiplus::VertexFinderwithDL::GetPairsEncoderDecoderTracks(), lcfiplus::Helix::Helix(), KalTrk::KalTrk(), lcfiplus::TrackPocaXY::operator()(), lcfiplus::MakeROOTFileCC::process(), lcfiplus::MakeROOTFileBB::process(), lcfiplus::algoSigProb::signedD0(), lcfiplus::algoSigProb::signedD0Significance(), and lcfiplus::algoSigProb::signedZ0().
getPos()
TVector3 lcfiplus::Track::getPos () const inline
getRadiusOfInnermostHit()
double lcfiplus::Track::getRadiusOfInnermostHit () const inline
Referenced by lcfiplus::TrackSelector::passesCut().
getSetHits()
int lcfiplus::Track::getSetHits () const inline
References lcfiplus::tpar::SET.
getSitHits()
int lcfiplus::Track::getSitHits () const inline
References lcfiplus::tpar::SIT.
getTanLambda()
double lcfiplus::Track::getTanLambda () const inline
References lcfiplus::tpar::td.
Referenced by lcfiplus::VertexFinderwithDL::GetPairsEncoderDecoderTracks(), lcfiplus::Helix::Helix(), KalTrk::KalTrk(), lcfiplus::MakeROOTFileCC::process(), lcfiplus::MakeROOTFileBB::process(), and lcfiplus::TestAlgoV0::process().
getTpcHits()
int lcfiplus::Track::getTpcHits () const inline
References lcfiplus::tpar::TPC.
Referenced by lcfiplus::TrackSelector::passesCut().
getVtxHits()
int lcfiplus::Track::getVtxHits () const inline
References lcfiplus::tpar::VTX.
Referenced by lcfiplus::TrackSelector::passesCut(), lcfiplus::VertexAnalysis::process(), and lcfiplus::algoSigProb::trackSelectionForFlavorTag().
getX()
double lcfiplus::Track::getX () const
References lcfiplus::tpar::d0, lcfiplus::tpar::om, and lcfiplus::tpar::ph.
Referenced by matchMcVertex(), lcfiplus::algoSigProb::signedD0(), lcfiplus::algoSigProb::signedD0Significance(), and lcfiplus::algoSigProb::trackD0Significance().
getY()
double lcfiplus::Track::getY () const
References lcfiplus::tpar::d0, lcfiplus::tpar::om, and lcfiplus::tpar::ph.
Referenced by matchMcVertex(), lcfiplus::algoSigProb::signedD0(), lcfiplus::algoSigProb::signedD0Significance(), and lcfiplus::algoSigProb::trackD0Significance().
getZ()
double lcfiplus::Track::getZ () const
References lcfiplus::tpar::om, and lcfiplus::tpar::z0.
Referenced by matchMcVertex(), and lcfiplus::algoSigProb::trackZ0Significance().
getZ0()
double lcfiplus::Track::getZ0 () const inline
References lcfiplus::tpar::z0.
Referenced by lcfiplus::EventNavigator::drawEvent(), lcfiplus::VertexFinderwithDL::GetPairsEncoderDecoderTracks(), lcfiplus::Helix::Helix(), KalTrk::KalTrk(), lcfiplus::VertexFinderSuehara::SortTracksByIPSig::operator()(), lcfiplus::TrackSelector::passesCut(), lcfiplus::MakeROOTFileCC::process(), lcfiplus::MakeROOTFileBB::process(), lcfiplus::TestAlgo::process(), lcfiplus::VertexAnalysis::process(), lcfiplus::algoSigProb::signedD0(), lcfiplus::algoSigProb::signedD0Significance(), lcfiplus::algoSigProb::signedZ0(), lcfiplus::algoEtc::SimpleSecElectronFinder(), lcfiplus::algoEtc::SimpleSecMuonFinder(), and testSuehara().
momentumAtVertex()
TVector3 lcfiplus::Track::momentumAtVertex (const Vertex * vtx) const
References lcfiplus::Vertex::getPos(), lcfiplus::Helix::GetPosDerivT(), lcfiplus::Helix::LogLikelihood(), and lcfiplus::PointBase::SECVTX.
Referenced by lcfiplus::TestAlgoV0::process().
setBNess()
void lcfiplus::Track::setBNess (double bness) inline
setCaloEdep()
void lcfiplus::Track::setCaloEdep (double * calo) inline
setCharge()
void lcfiplus::Track::setCharge (double charge) inline
setChi2()
void lcfiplus::Track::setChi2 (double chi2) inline
setCNess()
void lcfiplus::Track::setCNess (double cness) inline
setCorrEnergy()
void lcfiplus::Track::setCorrEnergy (double mass) inline
setCovMatrix()
void lcfiplus::Track::setCovMatrix (double * cov)
References lcfiplus::tpar::covN.
Referenced by lcfiplus::algoEtc::makeBeamTracks().
setFlightLength()
void lcfiplus::Track::setFlightLength (double flt) const inline
Referenced by lcfiplus::algoSigProb::signedD0(), lcfiplus::algoSigProb::signedD0Significance(), lcfiplus::algoSigProb::signedZ0(), lcfiplus::algoSigProb::trackD0Significance(), and lcfiplus::algoSigProb::trackZ0Significance().
setHelix() [1/2]
void lcfiplus::Track::setHelix (double d0, double z0, double phi, double omega, double tanLambda) inline
References lcfiplus::tpar::d0, lcfiplus::tpar::om, lcfiplus::tpar::ph, lcfiplus::tpar::td, and lcfiplus::tpar::z0.
Referenced by lcfiplus::algoEtc::makeBeamTracks().
setHelix() [2/2]
void lcfiplus::Track::setHelix (double * par) inline
setId()
void lcfiplus::Track::setId (int id) inline
Referenced by lcfiplus::algoEtc::makeBeamTracks(), and lcfiplus::LCIOStorer::SetEvent().
setMcp()
void lcfiplus::Track::setMcp (const lcfiplus::MCParticle * mcp) inline
setNdf()
void lcfiplus::Track::setNdf (int ndf) inline
setParticleIDProbability()
void lcfiplus::Track::setParticleIDProbability (string parName, double pidProbability) inline
setPDG()
void lcfiplus::Track::setPDG (int pdg) inline
setRadiusOfInnermostHit()
void lcfiplus::Track::setRadiusOfInnermostHit (double rimh) inline
setTrackHits()
void lcfiplus::Track::setTrackHits (int * hits) inline
swapEnergy()
void lcfiplus::Track::swapEnergy () inline
Referenced by lcfiplus::VertexMassRecovery::process().
The documentation for this class was generated from the following files:
lcfiplus.h
lcfiplus.cc