LCFIPlus: LcfiplusProcessor Class Reference
LcfiplusProcessor Class Reference
Marlin processor for LCFIPlus.
#include <LcfiplusProcessor.h>
Public Member Functions
virtual Processor * newProcessor ()
LcfiplusProcessor ()
virtual ~LcfiplusProcessor ()
virtual void init ()
Called at the begin of the job before anything is read.
virtual void processRunHeader (LCRunHeader *run)
Called for every run.
virtual void processEvent (LCEvent *evt)
Called for every event - the working horse.
virtual void check (LCEvent *evt)
virtual void end ()
Called after data processing for clean up.
virtual void RegisterCallback (const char *name, const char *classname, int flags)
Public Member Functions inherited from lcfiplus::EventStoreObserver
EventStoreObserver ()
virtual ~EventStoreObserver ()
virtual void GetCallback (const char *, const char *)
Detailed Description
Marlin processor for LCFIPlus.
Author
Tomohiko Tanabe, ICEPP, The University of Tokyo
Taikan Suehara, ICEPP, The University of Tokyo
Version
$Id$
Constructor & Destructor Documentation
LcfiplusProcessor()
LcfiplusProcessor::LcfiplusProcessor ()
~LcfiplusProcessor()
LcfiplusProcessor::~LcfiplusProcessor () virtual
Member Function Documentation
check()
void LcfiplusProcessor::check (LCEvent * evt) virtual
end()
void LcfiplusProcessor::end () virtual
Called after data processing for clean up.
init()
void LcfiplusProcessor::init () virtual
Called at the begin of the job before anything is read.
References lcfiplus::Parameters::add(), lcfiplus::LCIOStorer::getIgnoreLackOfVertexRP(), lcfiplus::LCIOStorer::getReadSubdetectorEnergies(), lcfiplus::LCIOStorer::getTrackHitOrdering(), lcfiplus::LCIOStorer::getUpdateVertexRPDaughters(), lcfiplus::Algorithm::init(), lcfiplus::LCIOStorer::InitMCPPFOCollections(), lcfiplus::LCIOStorer::InitPFOCollections(), lcfiplus::LCIOStorer::setIgnoreLackOfVertexRP(), lcfiplus::LCIOStorer::setParticleIDAlgorithmName(), lcfiplus::LCIOStorer::setReadSubdetectorEnergies(), lcfiplus::LCIOStorer::setTrackHitOrdering(), lcfiplus::LCIOStorer::setUpdateVertexRPDaughters(), SLM, and lcfiplus::Exception::what().
newProcessor()
virtual Processor* LcfiplusProcessor::newProcessor () inline virtual
processEvent()
void LcfiplusProcessor::processEvent (LCEvent * evt) virtual
Called for every event - the working horse.
References lcfiplus::Exception::what().
processRunHeader()
void LcfiplusProcessor::processRunHeader (LCRunHeader * run) virtual
Called for every run.
RegisterCallback()
void LcfiplusProcessor::RegisterCallback (const char * name, const char * classname, int flags) virtual
Reimplemented from lcfiplus::EventStoreObserver.
The documentation for this class was generated from the following files:
LcfiplusProcessor.h
LcfiplusProcessor.cc