LCFIPlus: lcfiplus::Point Class Reference
lcfiplus::Point Class Reference
#include <geometry.h>
Public Types
typedef ROOT::Math::SVector< double, 3 > SVector3
typedef ROOT::Math::SMatrix< double, 3, 3, ROOT::Math::MatRepSym< double, 3 > > SMatrixSym3
Public Types inherited from lcfiplus::PointBase
enum FITFLAG { NOTUSED, PRIVTX, SECVTX }
Public Member Functions
double LogLikelihood (const TVector3 &p) const
void LogLikelihoodDeriv (const TVector3 &p, double *output) const
Point (FITFLAG flag)
Point (const SVector3 &pos, const SMatrixSym3 &err, FITFLAG flag)
Point (const Point &ref, FITFLAG flag)
Point (const Vertex *vtx, FITFLAG flag)
~Point ()
void SetPosErr (const SVector3 &pos, const SMatrixSym3 &err)
double GetErr (int i, int j) const
TVector3 GetPos () const
Public Member Functions inherited from lcfiplus::PointBase
virtual ~PointBase ()
Additional Inherited Members
Protected Member Functions inherited from lcfiplus::PointBase
PointBase (FITFLAG flag)
FITFLAG GetFlag () const
Protected Attributes inherited from lcfiplus::PointBase
FITFLAG _fitflag
Member Typedef Documentation
SMatrixSym3
typedef ROOT::Math::SMatrix<double, 3,3,ROOT::Math::MatRepSym<double,3> > lcfiplus::Point::SMatrixSym3
SVector3
typedef ROOT::Math::SVector<double, 3> lcfiplus::Point::SVector3
Constructor & Destructor Documentation
Point() [1/4]
lcfiplus::Point::Point (FITFLAG flag) inline
Point() [2/4]
lcfiplus::Point::Point (const SVector3 & pos, const SMatrixSym3 & err, FITFLAG flag) inline
Point() [3/4]
lcfiplus::Point::Point (const Point & ref, FITFLAG flag) inline
Point() [4/4]
lcfiplus::Point::Point (const Vertex * vtx, FITFLAG flag)
References lcfiplus::Vertex::getCov(), lcfiplus::Vertex::getX(), lcfiplus::Vertex::getY(), lcfiplus::Vertex::getZ(), lcfiplus::Vertex::xx, lcfiplus::Vertex::xy, lcfiplus::Vertex::xz, lcfiplus::Vertex::yy, lcfiplus::Vertex::yz, and lcfiplus::Vertex::zz.
~Point()
lcfiplus::Point::~Point () inline
Member Function Documentation
GetErr()
double lcfiplus::Point::GetErr (int i, int j) const inline
Referenced by lcfiplus::VertexFitterSimple< Iterator >::operator()().
GetPos()
TVector3 lcfiplus::Point::GetPos () const inline
Referenced by lcfiplus::VertexFitterSimple< Iterator >::getChi2(), lcfiplus::GeometryHandler::HelixPointFit(), lcfiplus::Helix::LongitudinalDeviation(), and lcfiplus::VertexFitterSimple< Iterator >::operator()().
LogLikelihood()
double lcfiplus::Point::LogLikelihood (const TVector3 & p) const virtual
Implements lcfiplus::PointBase.
LogLikelihoodDeriv()
void lcfiplus::Point::LogLikelihoodDeriv (const TVector3 & p, double * output) const virtual
Implements lcfiplus::PointBase.
SetPosErr()
void lcfiplus::Point::SetPosErr (const SVector3 & pos, const SMatrixSym3 & err) inline
Referenced by lcfiplus::GeometryHandler::PointFit().
The documentation for this class was generated from the following files:
geometry.h
geometry.cc