LCFIPlus: lcfiplus::Exception Class Reference
lcfiplus::Exception Class Reference
#include <lcfiplus.h>
Public Member Functions
Exception (const char *message)
virtual ~Exception () throw ()
virtual const char * what () const throw ()
void Print ()
Constructor & Destructor Documentation
Exception()
lcfiplus::Exception::Exception (const char * message) inline
~Exception()
virtual lcfiplus::Exception::~Exception () throw () inline virtual
Member Function Documentation
Print()
void lcfiplus::Exception::Print () inline
Referenced by testSuehara().
what()
virtual const char* lcfiplus::Exception::what () const throw () inline virtual
Referenced by LcfiplusProcessor::init(), and LcfiplusProcessor::processEvent().
The documentation for this class was generated from the following file:
lcfiplus.h