LCFIPlus: lcfiplus::Event Class Reference
lcfiplus::Event Class Reference
#include <lcfiplus.h>
Public Member Functions
~Event ()
const vector< const Track * > & getTracks (const char *trackname=0) const
const vector< const Neutral * > & getNeutrals (const char *neutralname=0) const
const vector< const MCParticle * > & getMCParticles (const char *mcpname=0) const
const vector< const MCColorSinglet * > & getMCColorSinglets (const char *mcpname=0) const
const Vertex * getPrimaryVertex (const char *privtxname=0) const
const vector< const Vertex * > & getSecondaryVertices (const char *secvtxname=0) const
const vector< const Jet * > & getJets (const char *jetname=0) const
void setDefaultTracks (const char *name)
void setDefaultNeutrals (const char *name)
void setDefaultMCParticles (const char *name)
void setDefaultPrimaryVertex (const char *name)
void setDefaultSecondaryVertices (const char *name)
void setDefaultJets (const char *name)
const char * getDefaultTracks () const
const char * getDefaultNeutrals () const
const char * getDefaultMCParticles () const
const char * getDefaultPrimaryVertex () const
const char * getDefaultSecondaryVertices () const
const char * getDefaultJets () const
const MCParticle * getMCParticle (int id) const
const MCParticle * getMCParticle (const Track *trk) const
vector< const MCParticle * > mcGetColorStrings () const
int mcNumberOfB () const
int mcNumberOfC () const
vector< const MCParticle * > mcGetSemiStableBs () const
vector< const MCParticle * > mcGetSemiStableCs () const
vector< const MCParticle * > mcGetSemiStableBCs (bool separatebc) const
int mcFindParent (MCParticleVec &vec, const MCParticle *p) const
Public Member Functions inherited from lcfiplus::EventStore
void RegisterObserver (EventStoreObserver *observer)
void UnregisterObserver (EventStoreObserver *observer)
int Count (const char *name) const
bool IsExist (const char *name) const
bool IsExist (const char *name, const char *classname) const
const char * GetClassName (const char *name, int idx=0) const
void * GetObject (const char *name, const char *classname="") const
template<typename T >
bool Get (const char *name, const vector< const T *> *&buf) const
template<typename T >
bool Get (const char *name, const vector< T *> *&buf) const
template<typename T >
bool Get (const char *name, const vector< T > *&buf) const
template<typename T >
bool Get (const char *name, const T *&buf) const
void * RegisterObject (const char *name, const char *classname, int flags=0)
template<typename T >
bool Register (const char *name, vector< T *> *&buf, int flags=0)
template<typename T >
bool Register (const char *name, vector< T > *&buf, int flags=0)
template<typename T >
bool Register (const char *name, T *&buf, int flags=0)
void Print () const
void ClearObjects ()
virtual ~EventStore ()
const multimap< string, lcfiplus::EventStore::StoredEntry > & GetObjectMap () const
Static Public Member Functions
static Event * Instance ()
Additional Inherited Members
Public Types inherited from lcfiplus::EventStore
enum { DO_NOT_DELETE = 0x0001, PERSIST = 0x0002, JET_WRITE_VERTEX = 0x1000 }
Protected Member Functions inherited from lcfiplus::EventStore
void *const & GetObjectRef (const char *name, const char *classname="") const
EventStore ()
Constructor & Destructor Documentation
~Event()
lcfiplus::Event::~Event ()
Member Function Documentation
getDefaultJets()
const char* lcfiplus::Event::getDefaultJets () const inline
getDefaultMCParticles()
const char* lcfiplus::Event::getDefaultMCParticles () const inline
getDefaultNeutrals()
const char* lcfiplus::Event::getDefaultNeutrals () const inline
getDefaultPrimaryVertex()
const char* lcfiplus::Event::getDefaultPrimaryVertex () const inline
getDefaultSecondaryVertices()
const char* lcfiplus::Event::getDefaultSecondaryVertices () const inline
getDefaultTracks()
const char* lcfiplus::Event::getDefaultTracks () const inline
getJets()
const vector< const Jet * > & lcfiplus::Event::getJets (const char * jetname = 0) const
References lcfiplus::EventStore::GetObjectRef().
getMCColorSinglets()
MCColorSingletVec & lcfiplus::Event::getMCColorSinglets (const char * mcpname = 0) const
References lcfiplus::EventStore::GetObjectRef().
getMCParticle() [1/2]
const MCParticle * lcfiplus::Event::getMCParticle (int id) const
References lcfiplus::MCParticle::getId(), and getMCParticles().
Referenced by lcfiplus::findTearDownVertices(), and matchMcVertexJet().
getMCParticle() [2/2]
const MCParticle * lcfiplus::Event::getMCParticle (const Track * trk) const
References lcfiplus::Track::getMcp().
getMCParticles()
MCParticleVec & lcfiplus::Event::getMCParticles (const char * mcpname = 0) const
References lcfiplus::EventStore::GetObjectRef().
Referenced by getMCParticle(), mcGetColorStrings(), mcGetSemiStableBCs(), mcGetSemiStableBs(), mcGetSemiStableCs(), mcNumberOfB(), mcNumberOfC(), lcfiplus::ZHHAlgo::process(), and lcfiplus::VertexAnalysis::process().
getNeutrals()
NeutralVec & lcfiplus::Event::getNeutrals (const char * neutralname = 0) const
References lcfiplus::EventStore::GetObjectRef().
Referenced by matchMcVertexRecoV0(), and lcfiplus::ZHHAlgo::process().
getPrimaryVertex()
const Vertex * lcfiplus::Event::getPrimaryVertex (const char * privtxname = 0) const
References lcfiplus::EventStore::GetObject().
Referenced by lcfiplus::Jet::getAllTracks(), lcfiplus::ZHHAlgo::process(), lcfiplus::TestAlgo::process(), and lcfiplus::VertexAnalysis::process().
getSecondaryVertices()
const vector< const Vertex * > & lcfiplus::Event::getSecondaryVertices (const char * secvtxname = 0) const
References lcfiplus::EventStore::GetObjectRef().
getTracks()
TrackVec & lcfiplus::Event::getTracks (const char * trackname = 0) const
References lcfiplus::EventStore::GetObjectRef().
Referenced by lcfiplus::JetMCMatch(), matchMcVertex(), matchMcVertexJet(), lcfiplus::ZHHAlgo::process(), and lcfiplus::VertexAnalysis::process().
Instance()
Event * lcfiplus::Event::Instance () static
Referenced by lcfiplus::EventNavigator::Fwd(), lcfiplus::Jet::getAllTracks(), lcfiplus::VertexMassRecovery::init(), lcfiplus::PrimaryVertexFinder::init(), lcfiplus::VertexFindingwithDL::init(), lcfiplus::VertexNtuple::init(), lcfiplus::TrackNtuple::init(), lcfiplus::FlavorTag::init(), lcfiplus::BuildUpVertex::init(), lcfiplus::JetClustering::init(), lcfiplus::JetVertexRefiner::init(), lcfiplus::TestAlgo::init(), lcfiplus::FlavtagReader::init(), lcfiplus::JetMCMatch(), lcfiplus::VertexMassRecovery::process(), lcfiplus::PrimaryVertexFinder::process(), lcfiplus::MakeROOTFileCC::process(), lcfiplus::VertexFindingwithDL::process(), lcfiplus::VertexNtuple::process(), lcfiplus::TrackNtuple::process(), lcfiplus::FlavorTag::process(), lcfiplus::BuildUpVertex::process(), lcfiplus::JetClustering::process(), lcfiplus::JetVertexRefiner::process(), lcfiplus::MakeROOTFileBB::process(), lcfiplus::ZHHAlgo::process(), lcfiplus::TestAlgo::process(), lcfiplus::VertexAnalysis::process(), lcfiplus::FlavtagReader::process(), lcfiplus::TestAlgoV0::process(), lcfiplus::TreeStorer::Register(), testSuehara(), and testTomohiko().
mcFindParent()
int lcfiplus::Event::mcFindParent (MCParticleVec & vec, const MCParticle * p) const
References lcfiplus::MCParticle::isParent().
mcGetColorStrings()
vector< const MCParticle * > lcfiplus::Event::mcGetColorStrings () const
References lcfiplus::MCParticle::getColorString(), and getMCParticles().
mcGetSemiStableBCs()
vector< const MCParticle * > lcfiplus::Event::mcGetSemiStableBCs (bool separatebc) const
References getMCParticles(), lcfiplus::MCParticle::getSemiStableBParent(), and lcfiplus::MCParticle::getSemiStableCParent().
mcGetSemiStableBs()
vector< const MCParticle * > lcfiplus::Event::mcGetSemiStableBs () const
References getMCParticles(), and lcfiplus::MCParticle::getSemiStableBParent().
mcGetSemiStableCs()
vector< const MCParticle * > lcfiplus::Event::mcGetSemiStableCs () const
References getMCParticles(), and lcfiplus::MCParticle::getSemiStableCParent().
mcNumberOfB()
int lcfiplus::Event::mcNumberOfB () const
References getMCParticles(), and lcfiplus::MCParticle::isSemiStableB().
mcNumberOfC()
int lcfiplus::Event::mcNumberOfC () const
References getMCParticles(), and lcfiplus::MCParticle::isSemiStableC().
setDefaultJets()
void lcfiplus::Event::setDefaultJets (const char * name) inline
setDefaultMCParticles()
void lcfiplus::Event::setDefaultMCParticles (const char * name) inline
setDefaultNeutrals()
void lcfiplus::Event::setDefaultNeutrals (const char * name) inline
setDefaultPrimaryVertex()
void lcfiplus::Event::setDefaultPrimaryVertex (const char * name) inline
Referenced by lcfiplus::PrimaryVertexFinder::init(), lcfiplus::VertexFindingwithDL::init(), lcfiplus::VertexNtuple::init(), lcfiplus::TrackNtuple::init(), lcfiplus::FlavorTag::init(), lcfiplus::BuildUpVertex::init(), lcfiplus::TestAlgo::init(), and lcfiplus::FlavtagReader::init().
setDefaultSecondaryVertices()
void lcfiplus::Event::setDefaultSecondaryVertices (const char * name) inline
Referenced by lcfiplus::TestAlgo::init().
setDefaultTracks()
void lcfiplus::Event::setDefaultTracks (const char * name) inline
The documentation for this class was generated from the following files:
lcfiplus.h
lcfiplus.cc