LCFIPlus: lcfiplus::VertexFinderSuehara Namespace Reference
lcfiplus::VertexFinderSuehara Namespace Reference
Classes
class SortTracksByIPSig
class VertexFinderSueharaConfig
Functions
bool VertexNearer (const Vertex *vtx1, const Vertex *vtx2)
bool VertexProbLarger (const Vertex *vtx1, const Vertex *vtx2)
void GetVertexList (list< const Track *> &tracks, const Vertex *ip, vector< Vertex *> &vtx, vector< Vertex *> &v0vtx, VertexFinderSueharaConfig &cfg)
lcfiplus::Vertex * associateTracks (Vertex *vertex, const VertexVec &v0vtx, list< const Track *> &tracks, VertexFinderSueharaConfig &cfg, list< const Track *> *residualTracks=0)
void associateIPTracks (vector< Vertex *> &vertices, Vertex *ip, VertexFinderSueharaConfig &cfg)
void associateIPTracksAVF (vector< Vertex *> &vertices, Vertex *ip, VertexFinderSueharaConfig &cfg)
void buildUp (TrackVec &tracks, vector< Vertex *> &vtx, vector< Vertex *> &v0vtx, double chi2thpri, VertexFinderSueharaConfig &cfg, Vertex **ip=0)
void buildUpForJetClustering (TrackVec &tracks, vector< Vertex *> &vtx)
vector< Vertex * > makeSingleTrackVertices (VertexVec &vtcs, TrackVec &tracks, VertexVec &v0vtx, const Vertex *ip, VertexFinderSueharaConfig &cfg)
vector< Vertex * > makeSingleTrackVertices (Jet *jet, TrackVec &tracks, VertexVec &v0vtx, const Vertex *ip, VertexFinderSueharaConfig &cfg)
void recombineVertices (vector< Vertex *> &vertices, vector< Vertex *> &singleVertices)
void recombineVertices (vector< Vertex *> &vertices, vector< Vertex *> &singleVertices, VertexFinderSueharaConfig &cfg)
void optimizeTwoVertices (Vertex *&v1, Vertex *&v2, int nvr)
Function Documentation
associateIPTracks()
void lcfiplus::VertexFinderSuehara::associateIPTracks (vector< Vertex *> & vertices, Vertex * ip, VertexFinderSueharaConfig & cfg)
Referenced by lcfiplus::BuildUpVertex::process().
associateIPTracksAVF()
void lcfiplus::VertexFinderSuehara::associateIPTracksAVF (vector< Vertex *> & vertices, Vertex * ip, VertexFinderSueharaConfig & cfg)
References lcfiplus::VertexFinderSuehara::VertexFinderSueharaConfig::chi2th, lcfiplus::Helix::ClosePoint(), lcfiplus::tpar::d0d0, lcfiplus::Vertex::getChi2Track(), lcfiplus::Vertex::getId(), lcfiplus::Vertex::getPos(), lcfiplus::Vertex::getTracks(), lcfiplus::algoEtc::makeBeamVertex(), lcfiplus::VertexFinderSuehara::VertexFinderSueharaConfig::minimumdistIP, lcfiplus::PointBase::SECVTX, lcfiplus::VertexFinderSuehara::VertexFinderSueharaConfig::temperature, lcfiplus::verbose, lcfiplus::Vertex::xx, lcfiplus::Vertex::yy, lcfiplus::tpar::z0z0, and lcfiplus::Vertex::zz.
Referenced by lcfiplus::BuildUpVertex::process().
associateTracks()
Vertex * lcfiplus::VertexFinderSuehara::associateTracks (Vertex * vertex, const VertexVec & v0vtx, list< const Track *> & tracks, VertexFinderSueharaConfig & cfg, list< const Track *> * residualTracks = 0)
Referenced by GetVertexList().
buildUp()
void lcfiplus::VertexFinderSuehara::buildUp (TrackVec & tracks, vector< Vertex *> & vtx, vector< Vertex *> & v0vtx, double chi2thpri, VertexFinderSueharaConfig & cfg, Vertex ** ip = 0)
References lcfiplus::findPrimaryVertex().
Referenced by lcfiplus::BuildUpVertex::process().
buildUpForJetClustering()
void lcfiplus::VertexFinderSuehara::buildUpForJetClustering (TrackVec & tracks, vector< Vertex *> & vtx)
GetVertexList()
void lcfiplus::VertexFinderSuehara::GetVertexList (list< const Track *> & tracks, const Vertex * ip, vector< Vertex *> & vtx, vector< Vertex *> & v0vtx, VertexFinderSueharaConfig & cfg)
References associateTracks(), lcfiplus::VertexFinderSuehara::VertexFinderSueharaConfig::avf, lcfiplus::VertexFinderSuehara::VertexFinderSueharaConfig::chi2th, lcfiplus::VertexFinderSuehara::VertexFinderSueharaConfig::chi2thV0SelTrack, lcfiplus::constVector(), lcfiplus::Vertex::getChi2Track(), lcfiplus::Vertex::getCov(), lcfiplus::Vertex::getPos(), lcfiplus::Vertex::getProb(), lcfiplus::Vertex::getTracks(), lcfiplus::Vertex::getVertexMass(), lcfiplus::Vertex::getX(), lcfiplus::Vertex::getY(), lcfiplus::Vertex::getZ(), lcfiplus::VertexFinderSuehara::VertexFinderSueharaConfig::massth, lcfiplus::algoEtc::min(), lcfiplus::Vertex::setVertexingName(), lcfiplus::VertexFinderSuehara::VertexFinderSueharaConfig::v0selTrack, lcfiplus::VertexFinderSuehara::VertexFinderSueharaConfig::v0selVertex, lcfiplus::verbose, VertexProbLarger(), lcfiplus::Vertex::xx, lcfiplus::Vertex::xy, lcfiplus::Vertex::xz, lcfiplus::Vertex::yy, lcfiplus::Vertex::yz, and lcfiplus::Vertex::zz.
makeSingleTrackVertices() [1/2]
vector< Vertex * > lcfiplus::VertexFinderSuehara::makeSingleTrackVertices (VertexVec & vtcs, TrackVec & tracks, VertexVec & v0vtx, const Vertex * ip, VertexFinderSueharaConfig & cfg)
Referenced by testSuehara().
makeSingleTrackVertices() [2/2]
vector< Vertex * > lcfiplus::VertexFinderSuehara::makeSingleTrackVertices (Jet * jet, TrackVec & tracks, VertexVec & v0vtx, const Vertex * ip, VertexFinderSueharaConfig & cfg)
optimizeTwoVertices()
void lcfiplus::VertexFinderSuehara::optimizeTwoVertices (Vertex *& v1, Vertex *& v2, int nvr)
References lcfiplus::Vertex::getChi2(), lcfiplus::Vertex::getChi2Track(), lcfiplus::Vertex::getProb(), and lcfiplus::Vertex::getTracks().
recombineVertices() [1/2]
void lcfiplus::VertexFinderSuehara::recombineVertices (vector< Vertex *> & vertices, vector< Vertex *> & singleVertices)
Referenced by testSuehara().
recombineVertices() [2/2]
void lcfiplus::VertexFinderSuehara::recombineVertices (vector< Vertex *> & vertices, vector< Vertex *> & singleVertices, VertexFinderSueharaConfig & cfg)
VertexNearer()
bool lcfiplus::VertexFinderSuehara::VertexNearer (const Vertex * vtx1, const Vertex * vtx2)
References lcfiplus::Vertex::getPos().
VertexProbLarger()
bool lcfiplus::VertexFinderSuehara::VertexProbLarger (const Vertex * vtx1, const Vertex * vtx2)
References lcfiplus::Vertex::getProb().
Referenced by GetVertexList().