LCFIPlus: lcfiplus::VertexFinderPerfect Namespace Reference
lcfiplus::VertexFinderPerfect Namespace Reference
Functions
void findPerfectVertices (TrackVec &tracks, MCParticleVec &mcp, vector< MCVertex *> &selvtx, int minimumRecoTracks, double minimumDistance=0.1, bool print=false)
Function Documentation
findPerfectVertices()
void lcfiplus::VertexFinderPerfect::findPerfectVertices (TrackVec & tracks, MCParticleVec & mcp, vector< MCVertex *> & selvtx, int minimumRecoTracks, double minimumDistance = 0.1, bool print = false)
References lcfiplus::MCVertex::add(), lcfiplus::MCParticle::getPDG(), lcfiplus::MCParticle::getSemiStableParent(), lcfiplus::MCParticle::setParent(), lcfiplus::MCVertex::setParent(), and lcfiplus::MCVertex::setPos().
Referenced by lcfiplus::FtMCNB::processEvent(), lcfiplus::FtMCNC::processEvent(), and testSuehara().