LCFIPlus: lcfiplus::algoSigProb Namespace Reference
lcfiplus::algoSigProb Namespace Reference
Functions
bool trackSelectionForFlavorTag (const Track *trk, int nHitCut)
double trackD0Significance (const Track *trk, const Vertex *pri)
double trackZ0Significance (const Track *trk, const Vertex *pri)
double signedD0Significance (const Track *trk, const Jet *jet, const Vertex *pri, bool updateFlt=false)
double signedZ0Significance (const Track *trk, const Jet *jet, const Vertex *pri, bool updateFlt=false)
double signedD0 (const Track *trk, const Jet *jet, const Vertex *pri, bool updateFlt=false)
double signedZ0 (const Track *trk, const Jet *jet, const Vertex *pri, bool updateFlt=false)
void findMostSignificantTrack (const Jet *jet, const Vertex *pri, int minhitcut, double sigVec[6])
double prob1D (double sig, double maxsig, double *pars)
double trackProbD0 (const Track *trk, const Vertex *pri)
double trackProbZ0 (const Track *trk, const Vertex *pri)
double jointProbD0 (const Jet *jet, const Vertex *pri, int minhitcut, double maxd0sigcut=1e+300, bool useVertexTracks=true)
double jointProbZ0 (const Jet *jet, const Vertex *pri, int minhitcut, double maxz0sigcut=1e+300, bool useVertexTracks=true)
double jointProb2D0 (const Jet *jet, const Vertex *pri, int minhitcut, double maxd0sigcut, bool useVertexTracks, const TH1 *jh1, const TH1 *jh2)
double jointProb2Z0 (const Jet *jet, const Vertex *pri, int minhitcut, double maxz0sigcut, bool useVertexTracks, const TH1 *jh1, const TH1 *jh2)
double prob1D2 (double sig, double, const TH1 *jh1, const TH1 *jh2)
Variables
double rpars [7]
double zpars [7]
Function Documentation
findMostSignificantTrack()
void lcfiplus::algoSigProb::findMostSignificantTrack (const Jet * jet, const Vertex * pri, int minhitcut, double sigVec[6])
References lcfiplus::Jet::getAllTracks(), signedD0Significance(), signedZ0Significance(), and trackSelectionForFlavorTag().
Referenced by lcfiplus::FtTrk1D0Sig::process(), lcfiplus::FtTrk2D0Sig::process(), lcfiplus::FtTrk1Z0Sig::process(), lcfiplus::FtTrk2Z0Sig::process(), lcfiplus::FtTrk1Pt::process(), lcfiplus::FtTrk2Pt::process(), lcfiplus::FtTrk1PtByJetE::process(), and lcfiplus::FtTrk2PtByJetE::process().
jointProb2D0()
double lcfiplus::algoSigProb::jointProb2D0 (const Jet * jet, const Vertex * pri, int minhitcut, double maxd0sigcut, bool useVertexTracks, const TH1 * jh1, const TH1 * jh2)
References lcfiplus::Jet::getAllTracks(), lcfiplus::Jet::getTracks(), prob1D2(), trackD0Significance(), and trackSelectionForFlavorTag().
Referenced by lcfiplus::FtJProbR2::process(), and lcfiplus::FtJProbR25Sigma::process().
jointProb2Z0()
double lcfiplus::algoSigProb::jointProb2Z0 (const Jet * jet, const Vertex * pri, int minhitcut, double maxz0sigcut, bool useVertexTracks, const TH1 * jh1, const TH1 * jh2)
References lcfiplus::Jet::getAllTracks(), lcfiplus::Jet::getTracks(), prob1D2(), trackSelectionForFlavorTag(), and trackZ0Significance().
Referenced by lcfiplus::FtJProbZ2::process(), and lcfiplus::FtJProbZ25Sigma::process().
jointProbD0()
double lcfiplus::algoSigProb::jointProbD0 (const Jet * jet, const Vertex * pri, int minhitcut, double maxd0sigcut = 1e+300, bool useVertexTracks = true)
References lcfiplus::Jet::getAllTracks(), lcfiplus::Jet::getTracks(), prob1D(), rpars, trackD0Significance(), and trackSelectionForFlavorTag().
Referenced by lcfiplus::FtJProbR::process(), and lcfiplus::FtJProbR5Sigma::process().
jointProbZ0()
double lcfiplus::algoSigProb::jointProbZ0 (const Jet * jet, const Vertex * pri, int minhitcut, double maxz0sigcut = 1e+300, bool useVertexTracks = true)
References lcfiplus::Jet::getAllTracks(), lcfiplus::Jet::getTracks(), prob1D(), trackSelectionForFlavorTag(), trackZ0Significance(), and zpars.
Referenced by lcfiplus::FtJProbZ::process(), and lcfiplus::FtJProbZ5Sigma::process().
prob1D()
double lcfiplus::algoSigProb::prob1D (double sig, double maxsig, double * pars)
Referenced by jointProbD0(), jointProbZ0(), trackProbD0(), and trackProbZ0().
prob1D2()
double lcfiplus::algoSigProb::prob1D2 (double sig, double , const TH1 * jh1, const TH1 * jh2)
Referenced by jointProb2D0(), and jointProb2Z0().
signedD0()
double lcfiplus::algoSigProb::signedD0 (const Track * trk, const Jet * jet, const Vertex * pri, bool updateFlt = false)
References lcfiplus::tpar::d0, lcfiplus::Track::getD0(), lcfiplus::TrackPocaXY::getFlightLength(), lcfiplus::Track::getPhi(), lcfiplus::Track::getX(), lcfiplus::Vertex::getX(), lcfiplus::Track::getY(), lcfiplus::Vertex::getY(), lcfiplus::Track::getZ0(), and lcfiplus::Track::setFlightLength().
Referenced by lcfiplus::TrackNtuple::process(), lcfiplus::FtD0bProbSigned::process(), lcfiplus::FtD0cProbSigned::process(), and lcfiplus::FtD0qProbSigned::process().
signedD0Significance()
double lcfiplus::algoSigProb::signedD0Significance (const Track * trk, const Jet * jet, const Vertex * pri, bool updateFlt = false)
References lcfiplus::tpar::d0, lcfiplus::tpar::d0d0, lcfiplus::Vertex::getCov(), lcfiplus::Track::getCovMatrix(), lcfiplus::Track::getD0(), lcfiplus::TrackPocaXY::getFlightLength(), lcfiplus::Track::getPhi(), lcfiplus::Track::getX(), lcfiplus::Vertex::getX(), lcfiplus::Track::getY(), lcfiplus::Vertex::getY(), lcfiplus::Track::getZ0(), lcfiplus::Track::setFlightLength(), lcfiplus::Vertex::xx, and lcfiplus::Vertex::yy.
Referenced by findMostSignificantTrack(), lcfiplus::TrackNtuple::process(), lcfiplus::FtD0bProbIP::process(), and lcfiplus::FtD0cProbIP::process().
signedZ0()
double lcfiplus::algoSigProb::signedZ0 (const Track * trk, const Jet * jet, const Vertex * pri, bool updateFlt = false)
References lcfiplus::Track::getD0(), lcfiplus::TrackPocaXY::getFlightLength(), lcfiplus::Track::getPhi(), lcfiplus::Vertex::getZ(), lcfiplus::Track::getZ0(), and lcfiplus::Track::setFlightLength().
Referenced by lcfiplus::TrackNtuple::process(), and signedZ0Significance().
signedZ0Significance()
double lcfiplus::algoSigProb::signedZ0Significance (const Track * trk, const Jet * jet, const Vertex * pri, bool updateFlt = false)
References lcfiplus::Vertex::getCov(), lcfiplus::Track::getCovMatrix(), signedZ0(), lcfiplus::tpar::z0z0, and lcfiplus::Vertex::zz.
Referenced by findMostSignificantTrack(), lcfiplus::TrackNtuple::process(), lcfiplus::FtZ0bProbIP::process(), and lcfiplus::FtZ0cProbIP::process().
trackD0Significance()
double lcfiplus::algoSigProb::trackD0Significance (const Track * trk, const Vertex * pri)
References lcfiplus::tpar::d0, lcfiplus::tpar::d0d0, lcfiplus::Vertex::getCov(), lcfiplus::Track::getCovMatrix(), lcfiplus::TrackPocaXY::getFlightLength(), lcfiplus::Track::getX(), lcfiplus::Vertex::getX(), lcfiplus::Track::getY(), lcfiplus::Vertex::getY(), lcfiplus::Track::setFlightLength(), lcfiplus::Vertex::xx, and lcfiplus::Vertex::yy.
Referenced by jointProb2D0(), jointProbD0(), lcfiplus::FtD0bProb::process(), lcfiplus::FtD0bProb2::process(), lcfiplus::FtD0cProb::process(), lcfiplus::FtD0cProb2::process(), lcfiplus::FtD0qProb::process(), lcfiplus::FtD0qProb2::process(), lcfiplus::FtD0bProbSigned::process(), lcfiplus::FtD0cProbSigned::process(), lcfiplus::FtD0qProbSigned::process(), and trackProbD0().
trackProbD0()
double lcfiplus::algoSigProb::trackProbD0 (const Track * trk, const Vertex * pri)
References prob1D(), rpars, and trackD0Significance().
trackProbZ0()
double lcfiplus::algoSigProb::trackProbZ0 (const Track * trk, const Vertex * pri)
References prob1D(), trackZ0Significance(), and zpars.
trackSelectionForFlavorTag()
bool lcfiplus::algoSigProb::trackSelectionForFlavorTag (const Track * trk, int nHitCut)
References lcfiplus::Track::getFtdHits(), and lcfiplus::Track::getVtxHits().
Referenced by findMostSignificantTrack(), jointProb2D0(), jointProb2Z0(), jointProbD0(), jointProbZ0(), and lcfiplus::TrackNtuple::process().
trackZ0Significance()
double lcfiplus::algoSigProb::trackZ0Significance (const Track * trk, const Vertex * pri)
References lcfiplus::Vertex::getCov(), lcfiplus::Track::getCovMatrix(), lcfiplus::TrackPocaXY::getFlightLength(), lcfiplus::Track::getZ(), lcfiplus::Vertex::getZ(), lcfiplus::Track::setFlightLength(), lcfiplus::tpar::z0, lcfiplus::tpar::z0z0, and lcfiplus::Vertex::zz.
Referenced by jointProb2Z0(), jointProbZ0(), lcfiplus::FtZ0bProb::process(), lcfiplus::FtZ0bProb2::process(), lcfiplus::FtZ0cProb::process(), lcfiplus::FtZ0cProb2::process(), lcfiplus::FtZ0qProb::process(), lcfiplus::FtZ0qProb2::process(), and trackProbZ0().
Variable Documentation
rpars
double lcfiplus::algoSigProb::rpars[7]
Initial value:
= {
  1.19312,
  2.17842e-05,
  0.131316,
  6.27001e-06,
  0.630934,
  0.00012063,
  0.0165772
}
Referenced by jointProbD0(), and trackProbD0().
zpars
double lcfiplus::algoSigProb::zpars[7]
Initial value:
= {
  1.28694,
  2.64263e-05,
  0.121609,
  7.32101e-06,
  0.624213,
  0.000161151,
  0.0138247
}
Referenced by jointProbZ0(), and trackProbZ0().