LCFIPlus: lcfiplus::VertexFinderwithDL Namespace Reference
lcfiplus::VertexFinderwithDL Namespace Reference
Functions
std::vector< std::vector< double > > SliceN2DVector (std::vector< std::vector< double > > vec, int rowstart, int rowend, int colstart, int colend)
std::vector< std::vector< double > > ConcatN2DVector (std::vector< std::vector< double > > vec1, std::vector< std::vector< double > > vec2)
tensorflow::Tensor N2DVector2Tensor (std::vector< std::vector< double > > vec)
tensorflow::Tensor N3DVector2Tensor (std::vector< std::vector< std::vector< double > > > vec)
std::vector< std::vector< double > > Tensor2N2DVector (tensorflow::Tensor tensor)
std::vector< std::vector< std::vector< double > > > Tensor2N3DVector (tensorflow::Tensor tensor)
void DebugPrintGetEventData (std::vector< std::vector< double > > event_data, int ncomb, int NCombination)
void DebugPrintSecondarySort (std::vector< std::vector< double > > secondary_seeds)
void DebugPrintPrimarySort (std::vector< std::vector< double > > primary_seeds)
void DebugPrintGetTracks (std::vector< std::vector< double > > tracks)
void DebugPrintVLSTMPrediction (std::vector< std::vector< std::vector< double > > > scores)
std::vector< std::vector< double > > GetEventData (std::vector< std::vector< double > > variables, tensorflow::SavedModelBundleLite &pair_model_bundle, tensorflow::SavedModelBundleLite &pair_pos_model_bundle)
std::vector< std::vector< double > > GetRemainDecoderTracks (std::vector< std::vector< double > > decoder_tracks, std::vector< int > track_list)
std::vector< std::vector< double > > SecondarySeedSelection (std::vector< std::vector< double > > event_data, int ThresholdPairSecondaryScore, int ThresholdPairPosScore)
void PrintResults (std::vector< int > primary_track_list, std::vector< std::vector< int > > secondary_track_lists)
void GetPairsEncoderDecoderTracks (TrackVec &tracks, int NTrackVariable, int MaxTrack, std::vector< std::vector< double > > &pairs, std::vector< std::vector< double > > &encoder_tracks, std::vector< std::vector< double > > &decoder_tracks)
void PrimaryVertexFinder (bool debug, int MaxPrimaryVertexLoop, double ThresholdPrimaryScore, std::vector< std::vector< double > > event_data, std::vector< std::vector< double > > encoder_tracks, std::vector< std::vector< double > > decoder_tracks, tensorflow::SavedModelBundleLite &lstm_model_bundle, std::vector< int > &primary_track_list, std::vector< std::vector< std::vector< double > > > &primary_scores, std::vector< double > &bigger_primary_scores)
void SecondaryVertexFinder (bool debug, double ThresholdSecondaryScore, std::vector< double > primary_scores, std::vector< std::vector< double > > secondary_event_data, std::vector< std::vector< double > > encoder_tracks, std::vector< std::vector< double > > decoder_tracks, tensorflow::SavedModelBundleLite &slstm_model_bundle, std::vector< int > &primary_track_list, std::vector< std::vector< int > > &secondary_track_lists)
std::vector< std::vector< int > > MergeSingleTrack (TrackVec &tracks, std::vector< std::vector< int > > secondary_track_lists)
void PrimarySecondaryVertices (TrackVec &tracks, std::vector< int > primary_track_list, std::vector< std::vector< int > > secondary_track_lists, Vertex &vtx, std::vector< Vertex *> &vtces)
Function Documentation
ConcatN2DVector()
std::vector< std::vector< double > > lcfiplus::VertexFinderwithDL::ConcatN2DVector (std::vector< std::vector< double > > vec1, std::vector< std::vector< double > > vec2)
Referenced by GetEventData().
DebugPrintGetEventData()
void lcfiplus::VertexFinderwithDL::DebugPrintGetEventData (std::vector< std::vector< double > > event_data, int ncomb, int NCombination)
DebugPrintGetTracks()
void lcfiplus::VertexFinderwithDL::DebugPrintGetTracks (std::vector< std::vector< double > > tracks)
Referenced by lcfiplus::VertexFindingwithDL::process().
DebugPrintPrimarySort()
void lcfiplus::VertexFinderwithDL::DebugPrintPrimarySort (std::vector< std::vector< double > > primary_seeds)
DebugPrintSecondarySort()
void lcfiplus::VertexFinderwithDL::DebugPrintSecondarySort (std::vector< std::vector< double > > secondary_seeds)
Referenced by lcfiplus::VertexFindingwithDL::process().
DebugPrintVLSTMPrediction()
void lcfiplus::VertexFinderwithDL::DebugPrintVLSTMPrediction (std::vector< std::vector< std::vector< double > > > scores)
Referenced by lcfiplus::VertexFindingwithDL::process(), and SecondaryVertexFinder().
GetEventData()
std::vector< std::vector< double > > lcfiplus::VertexFinderwithDL::GetEventData (std::vector< std::vector< double > > variables, tensorflow::SavedModelBundleLite & pair_model_bundle, tensorflow::SavedModelBundleLite & pair_pos_model_bundle)
References ConcatN2DVector(), N2DVector2Tensor(), and Tensor2N2DVector().
Referenced by lcfiplus::VertexFindingwithDL::process().
GetPairsEncoderDecoderTracks()
void lcfiplus::VertexFinderwithDL::GetPairsEncoderDecoderTracks (TrackVec & tracks, int NTrackVariable, int MaxTrack, std::vector< std::vector< double > > & pairs, std::vector< std::vector< double > > & encoder_tracks, std::vector< std::vector< double > > & decoder_tracks)
References lcfiplus::Track::getCharge(), lcfiplus::Track::getCovMatrix(), lcfiplus::Track::getD0(), lcfiplus::Track::getOmega(), lcfiplus::Track::getPhi(), lcfiplus::Track::getTanLambda(), and lcfiplus::Track::getZ0().
Referenced by lcfiplus::VertexFindingwithDL::process().
GetRemainDecoderTracks()
std::vector< std::vector< double > > lcfiplus::VertexFinderwithDL::GetRemainDecoderTracks (std::vector< std::vector< double > > decoder_tracks, std::vector< int > track_list)
Referenced by SecondaryVertexFinder().
MergeSingleTrack()
std::vector< std::vector< int > > lcfiplus::VertexFinderwithDL::MergeSingleTrack (TrackVec & tracks, std::vector< std::vector< int > > secondary_track_lists)
References lcfiplus::Vertex::getChi2().
Referenced by lcfiplus::VertexFindingwithDL::process().
N2DVector2Tensor()
tensorflow::Tensor lcfiplus::VertexFinderwithDL::N2DVector2Tensor (std::vector< std::vector< double > > vec)
Referenced by GetEventData(), PrimaryVertexFinder(), and SecondaryVertexFinder().
N3DVector2Tensor()
tensorflow::Tensor lcfiplus::VertexFinderwithDL::N3DVector2Tensor (std::vector< std::vector< std::vector< double > > > vec)
Referenced by PrimaryVertexFinder(), and SecondaryVertexFinder().
PrimarySecondaryVertices()
void lcfiplus::VertexFinderwithDL::PrimarySecondaryVertices (TrackVec & tracks, std::vector< int > primary_track_list, std::vector< std::vector< int > > secondary_track_lists, Vertex & vtx, std::vector< Vertex *> & vtces)
Referenced by lcfiplus::VertexFindingwithDL::process().
PrimaryVertexFinder()
void lcfiplus::VertexFinderwithDL::PrimaryVertexFinder (bool debug, int MaxPrimaryVertexLoop, double ThresholdPrimaryScore, std::vector< std::vector< double > > event_data, std::vector< std::vector< double > > encoder_tracks, std::vector< std::vector< double > > decoder_tracks, tensorflow::SavedModelBundleLite & lstm_model_bundle, std::vector< int > & primary_track_list, std::vector< std::vector< std::vector< double > > > & primary_scores, std::vector< double > & bigger_primary_scores)
References N2DVector2Tensor(), N3DVector2Tensor(), SliceN2DVector(), and Tensor2N3DVector().
Referenced by lcfiplus::VertexFindingwithDL::process().
PrintResults()
void lcfiplus::VertexFinderwithDL::PrintResults (std::vector< int > primary_track_list, std::vector< std::vector< int > > secondary_track_lists)
Referenced by lcfiplus::VertexFindingwithDL::process().
SecondarySeedSelection()
std::vector< std::vector< double > > lcfiplus::VertexFinderwithDL::SecondarySeedSelection (std::vector< std::vector< double > > event_data, int ThresholdPairSecondaryScore, int ThresholdPairPosScore)
Referenced by lcfiplus::VertexFindingwithDL::process().
SecondaryVertexFinder()
void lcfiplus::VertexFinderwithDL::SecondaryVertexFinder (bool debug, double ThresholdSecondaryScore, std::vector< double > primary_scores, std::vector< std::vector< double > > secondary_event_data, std::vector< std::vector< double > > encoder_tracks, std::vector< std::vector< double > > decoder_tracks, tensorflow::SavedModelBundleLite & slstm_model_bundle, std::vector< int > & primary_track_list, std::vector< std::vector< int > > & secondary_track_lists)
References DebugPrintVLSTMPrediction(), GetRemainDecoderTracks(), N2DVector2Tensor(), N3DVector2Tensor(), SliceN2DVector(), and Tensor2N3DVector().
Referenced by lcfiplus::VertexFindingwithDL::process().
SliceN2DVector()
std::vector< std::vector< double > > lcfiplus::VertexFinderwithDL::SliceN2DVector (std::vector< std::vector< double > > vec, int rowstart, int rowend, int colstart, int colend)
Referenced by PrimaryVertexFinder(), and SecondaryVertexFinder().
Tensor2N2DVector()
std::vector< std::vector< double > > lcfiplus::VertexFinderwithDL::Tensor2N2DVector (tensorflow::Tensor tensor)
Referenced by GetEventData().
Tensor2N3DVector()
std::vector< std::vector< std::vector< double > > > lcfiplus::VertexFinderwithDL::Tensor2N3DVector (tensorflow::Tensor tensor)
Referenced by PrimaryVertexFinder(), and SecondaryVertexFinder().